#! /bin/bash -e

EVTS=${1:128}

echo "m1"
cmsRun step3.py wf=-1 withl1=True n=$EVTS T2=True > logm1 2>&1

for frac in {10,20}
do
for nvtx in {10,20,30}

do
echo "m2"
cmsRun step3.py wf=-2 withl1=True n=$EVTS T2=True frac=$frac nvtx=$nvtx > logm2 2>&1 

wait
echo "m3"
cmsRun step3.py wf=-3 withl1=True n=$EVTS T2=True frac=$frac nvtx=$nvtx > logm3 2>&1 

wait
echo "m4"
cmsRun step3.py wf=-4 withl1=True n=$EVTS T2=True frac=$frac nvtx=$nvtx > logm4 2>&1 

wait
 
done
done

