import FWCore.ParameterSet.Config as cms

################ dqmoffline_step

PV0p1 = cms.EDProducer("TrackWithVertexSelector",
    copyExtras = cms.untracked.bool(False),
    copyTrajectories = cms.untracked.bool(False),
    d0Max = cms.double(999.0),
    dzMax = cms.double(999.0),
    etaMax = cms.double(5.0),
    etaMin = cms.double(0.0),
    nSigmaDtVertex = cms.double(0),
    nVertices = cms.uint32(1),
    normalizedChi2 = cms.double(999999.0),
    numberOfLostHits = cms.uint32(999),
    numberOfValidHits = cms.uint32(0),
    numberOfValidPixelHits = cms.uint32(0),
    ptErrorCut = cms.double(9999999.0),
    ptMax = cms.double(100000.0),
    ptMin = cms.double(0.0),
    quality = cms.string(''),
    rhoVtx = cms.double(999.0),
    src = cms.InputTag("generalTracks"),
    timeResosTag = cms.InputTag(""),
    timesTag = cms.InputTag(""),
    useVtx = cms.bool(True),
    vertexTag = cms.InputTag("trackingDQMgoodOfflinePrimaryVertices"),
    vtxFallback = cms.bool(True),
    zetaVtx = cms.double(0.1)
)


TrackMon_ckf = cms.EDProducer("TrackEfficiencyMonitor",
    AlgoName = cms.string('CKFTk'),
    FolderName = cms.string('Tracking/TrackParameters'),
    OutputFileName = cms.string('MonitorTrackEfficiency.root'),
    OutputMEsInRootFile = cms.bool(False),
    STATrackCollection = cms.InputTag("cosmicMuons"),
    TKTrackCollection = cms.InputTag("generalTracks"),
    deltaXBin = cms.int32(50),
    deltaXMax = cms.double(100),
    deltaXMin = cms.double(-100),
    deltaYBin = cms.int32(50),
    deltaYMax = cms.double(100),
    deltaYMin = cms.double(-100),
    isBFieldOff = cms.bool(False),
    muonCompatibleLayersBin = cms.int32(10),
    muonCompatibleLayersMax = cms.double(30),
    muonCompatibleLayersMin = cms.double(0),
    muonD0Bin = cms.int32(50),
    muonD0Max = cms.double(100),
    muonD0Min = cms.double(-100),
    muonEtaBin = cms.int32(50),
    muonEtaMax = cms.double(3.2),
    muonEtaMin = cms.double(-3.2),
    muonPhiBin = cms.int32(50),
    muonPhiMax = cms.double(0.0),
    muonPhiMin = cms.double(-3.2),
    muonXBin = cms.int32(50),
    muonXMax = cms.double(100),
    muonXMin = cms.double(-100),
    muonYBin = cms.int32(50),
    muonYMax = cms.double(100),
    muonYMin = cms.double(-100),
    muonZBin = cms.int32(50),
    muonZMax = cms.double(500),
    muonZMin = cms.double(-500),
    muoncoll = cms.InputTag("muons"),
    signDeltaXBin = cms.int32(50),
    signDeltaXMax = cms.double(5),
    signDeltaXMin = cms.double(-5),
    signDeltaYBin = cms.int32(50),
    signDeltaYMax = cms.double(5),
    signDeltaYMin = cms.double(-5),
    theMaxZ = cms.double(110.0),
    theRadius = cms.double(85.0),
    trackCompatibleLayersBin = cms.int32(10),
    trackCompatibleLayersMax = cms.double(30),
    trackCompatibleLayersMin = cms.double(0),
    trackD0Bin = cms.int32(50),
    trackD0Max = cms.double(100),
    trackD0Min = cms.double(-100),
    trackEfficiency = cms.bool(True),
    trackEtaBin = cms.int32(50),
    trackEtaMax = cms.double(3.2),
    trackEtaMin = cms.double(-3.2),
    trackPhiBin = cms.int32(50),
    trackPhiMax = cms.double(0.0),
    trackPhiMin = cms.double(-3.2),
    trackXBin = cms.int32(50),
    trackXMax = cms.double(100),
    trackXMin = cms.double(-100),
    trackYBin = cms.int32(50),
    trackYMax = cms.double(100),
    trackYMin = cms.double(-100),
    trackZBin = cms.int32(50),
    trackZMax = cms.double(500),
    trackZMin = cms.double(-500)
)


TrackSeedMonhighPtTripletStep = cms.EDProducer("TrackingMonitor",
**dict(
    [
        ("AbsDxyBin" , cms.int32(120) ),
        ("AbsDxyMax" , cms.double(60.0) ),
        ("AbsDxyMin" , cms.double(0.0) ),
        ("AlgoName" , cms.string('highPtTripletStep') ),
        ("BSFolderName" , cms.string('Tracking/TrackParameters/BeamSpotParameters') ),
        ("BXlumiSetup" , cms.PSet(
        BXlumiBin = cms.int32(400),
        BXlumiMax = cms.double(6000),
        BXlumiMin = cms.double(2000),
        lumi = cms.InputTag("lumiProducer"),
        lumiScale = cms.double(6.37)
    ) ),
        ("Chi2Bin" , cms.int32(50) ),
        ("Chi2Max" , cms.double(199.5) ),
        ("Chi2Min" , cms.double(-0.5) ),
        ("Chi2NDFBin" , cms.int32(50) ),
        ("Chi2NDFMax" , cms.double(19.5) ),
        ("Chi2NDFMin" , cms.double(-0.5) ),
        ("Chi2ProbBin" , cms.int32(100) ),
        ("Chi2ProbMax" , cms.double(1.0) ),
        ("Chi2ProbMin" , cms.double(0.0) ),
        ("ClusterLabels" , cms.vstring('Pix') ),
        ("DxyBin" , cms.int32(100) ),
        ("DxyErrBin" , cms.int32(200) ),
        ("DxyErrMax" , cms.double(0.1) ),
        ("DxyMax" , cms.double(0.5) ),
        ("DxyMin" , cms.double(-0.5) ),
        ("Eta2DBin" , cms.int32(26) ),
        ("EtaBin" , cms.int32(46) ),
        ("EtaMax" , cms.double(4.5) ),
        ("EtaMin" , cms.double(-4.5) ),
        ("FolderName" , cms.string('Tracking/TrackParameters/generalTracks') ),
        ("GoodPVtxBin" , cms.int32(200) ),
        ("GoodPVtxMax" , cms.double(200.0) ),
        ("GoodPVtxMin" , cms.double(0.0) ),
        ("LSBin" , cms.int32(2000) ),
        ("LSMax" , cms.double(2000.0) ),
        ("LSMin" , cms.double(0) ),
        ("LUMIBin" , cms.int32(700) ),
        ("LUMIMax" , cms.double(70000.0) ),
        ("LUMIMin" , cms.double(0.0) ),
        ("LongDCABins" , cms.int32(100) ),
        ("LongDCAMax" , cms.double(8.0) ),
        ("LongDCAMin" , cms.double(-8.0) ),
        ("MVABin" , cms.int32(100) ),
        ("MVAMax" , cms.double(1) ),
        ("MVAMin" , cms.double(-1) ),
        ("MVAProducers" , cms.vstring(
        'initialStepClassifier1', 
        'initialStepClassifier2'
    ) ),
        ("MeanHitBin" , cms.int32(30) ),
        ("MeanHitMax" , cms.double(29.5) ),
        ("MeanHitMin" , cms.double(-0.5) ),
        ("MeanLayBin" , cms.int32(25) ),
        ("MeanLayMax" , cms.double(24.5) ),
        ("MeanLayMin" , cms.double(-0.5) ),
        ("MeasurementState" , cms.string('ImpactPoint') ),
        ("NClusPxBin" , cms.int32(100) ),
        ("NClusPxMax" , cms.double(20000) ),
        ("NClusPxMin" , cms.double(-0.5) ),
        ("NClusStrBin" , cms.int32(500) ),
        ("NClusStrMax" , cms.double(199999.5) ),
        ("NClusStrMin" , cms.double(-0.5) ),
        ("NTrk2DBin" , cms.int32(50) ),
        ("NTrk2DMax" , cms.double(1999.5) ),
        ("NTrk2DMin" , cms.double(-0.5) ),
        ("PVBin" , cms.int32(125) ),
        ("PVFolderName" , cms.string('Tracking/PrimaryVertices') ),
        ("PVMax" , cms.double(249.5) ),
        ("PVMin" , cms.double(-0.5) ),
        ("PXBLayBin" , cms.int32(6) ),
        ("PXBLayMax" , cms.double(5.5) ),
        ("PXBLayMin" , cms.double(-0.5) ),
        ("PXFLayBin" , cms.int32(6) ),
        ("PXFLayMax" , cms.double(5.5) ),
        ("PXFLayMin" , cms.double(-0.5) ),
        ("Phi2DBin" , cms.int32(32) ),
        ("PhiBin" , cms.int32(32) ),
        ("PhiMax" , cms.double(3.141592654) ),
        ("PhiMin" , cms.double(-3.141592654) ),
        ("Quality" , cms.string('') ),
        ("RecHitBin" , cms.int32(40) ),
        ("RecHitMax" , cms.double(39.5) ),
        ("RecHitMin" , cms.double(-0.5) ),
        ("RecLayBin" , cms.int32(25) ),
        ("RecLayMax" , cms.double(24.5) ),
        ("RecLayMin" , cms.double(-0.5) ),
        ("RecLostBin" , cms.int32(10) ),
        ("RecLostMax" , cms.double(9.5) ),
        ("RecLostMin" , cms.double(-0.5) ),
        ("RegionCandidatePtBin" , cms.int32(100) ),
        ("RegionCandidatePtMax" , cms.double(1000) ),
        ("RegionCandidatePtMin" , cms.double(0) ),
        ("RegionCandidates" , cms.InputTag("") ),
        ("RegionProducer" , cms.InputTag("") ),
        ("RegionSeedingLayersProducer" , cms.InputTag("") ),
        ("RegionSizeBin" , cms.int32(20) ),
        ("RegionSizeMax" , cms.double(19.5) ),
        ("RegionSizeMin" , cms.double(-0.5) ),
        ("SeedCandBin" , cms.int32(20) ),
        ("SeedCandMax" , cms.double(19.5) ),
        ("SeedCandMin" , cms.double(-0.5) ),
        ("SeedDxyBin" , cms.int32(100) ),
        ("SeedDxyMax" , cms.double(0.5) ),
        ("SeedDxyMin" , cms.double(-0.5) ),
        ("SeedDzBin" , cms.int32(120) ),
        ("SeedDzMax" , cms.double(30.0) ),
        ("SeedDzMin" , cms.double(-30.0) ),
        ("SeedHitBin" , cms.int32(6) ),
        ("SeedHitMax" , cms.double(5.5) ),
        ("SeedHitMin" , cms.double(-0.5) ),
        ("SeedProducer" , cms.InputTag("highPtTripletStepSeeds") ),
        ("TCDxyBin" , cms.int32(100) ),
        ("TCDxyMax" , cms.double(100.0) ),
        ("TCDxyMin" , cms.double(-100.0) ),
        ("TCDzBin" , cms.int32(100) ),
        ("TCDzMax" , cms.double(400.0) ),
        ("TCDzMin" , cms.double(-400.0) ),
        ("TCHitBin" , cms.int32(40) ),
        ("TCHitMax" , cms.double(39.5) ),
        ("TCHitMin" , cms.double(-0.5) ),
        ("TCProducer" , cms.InputTag("highPtTripletStepTrackCandidates") ),
        ("TCSizeBin" , cms.int32(200) ),
        ("TCSizeMax" , cms.double(999.5) ),
        ("TCSizeMin" , cms.double(-0.5) ),
        ("TECLayBin" , cms.int32(15) ),
        ("TECLayMax" , cms.double(14.5) ),
        ("TECLayMin" , cms.double(-0.5) ),
        ("TIBLayBin" , cms.int32(6) ),
        ("TIBLayMax" , cms.double(5.5) ),
        ("TIBLayMin" , cms.double(-0.5) ),
        ("TIDLayBin" , cms.int32(6) ),
        ("TIDLayMax" , cms.double(5.5) ),
        ("TIDLayMin" , cms.double(-0.5) ),
        ("TOBLayBin" , cms.int32(10) ),
        ("TOBLayMax" , cms.double(9.5) ),
        ("TOBLayMin" , cms.double(-0.5) ),
        ("TTRHBuilder" , cms.string('WithTrackAngle') ),
        ("ThetaBin" , cms.int32(32) ),
        ("ThetaMax" , cms.double(3.2) ),
        ("ThetaMin" , cms.double(0.0) ),
        ("TkSeedSizeBin" , cms.int32(100) ),
        ("TkSeedSizeMax" , cms.double(30000) ),
        ("TkSeedSizeMin" , cms.double(0) ),
        ("TkSizeBin" , cms.int32(100) ),
        ("TkSizeMax" , cms.double(99.5) ),
        ("TkSizeMin" , cms.double(-0.5) ),
        ("TrackPBin" , cms.int32(100) ),
        ("TrackPMax" , cms.double(100) ),
        ("TrackPMin" , cms.double(0) ),
        ("TrackProducer" , cms.InputTag("generalTracks") ),
        ("TrackProducerForMVA" , cms.InputTag("initialStepTracks") ),
        ("TrackPt2DBin" , cms.int32(100) ),
        ("TrackPtBin" , cms.int32(100) ),
        ("TrackPtMax" , cms.double(100) ),
        ("TrackPtMin" , cms.double(0.1) ),
        ("TrackPxBin" , cms.int32(50) ),
        ("TrackPxMax" , cms.double(50.0) ),
        ("TrackPxMin" , cms.double(-50.0) ),
        ("TrackPyBin" , cms.int32(50) ),
        ("TrackPyMax" , cms.double(50.0) ),
        ("TrackPyMin" , cms.double(-50.0) ),
        ("TrackPzBin" , cms.int32(50) ),
        ("TrackPzMax" , cms.double(50.0) ),
        ("TrackPzMin" , cms.double(-50.0) ),
        ("TrackQBin" , cms.int32(8) ),
        ("TrackQMax" , cms.double(2.5) ),
        ("TrackQMin" , cms.double(-2.5) ),
        ("TransDCABins" , cms.int32(100) ),
        ("TransDCAMax" , cms.double(8.0) ),
        ("TransDCAMin" , cms.double(-8.0) ),
        ("VXBin" , cms.int32(100) ),
        ("VXMax" , cms.double(0.5) ),
        ("VXMin" , cms.double(-0.5) ),
        ("VYBin" , cms.int32(100) ),
        ("VYMax" , cms.double(0.5) ),
        ("VYMin" , cms.double(-0.5) ),
        ("VZBin" , cms.int32(100) ),
        ("VZBinProf" , cms.int32(100) ),
        ("VZMax" , cms.double(30.0) ),
        ("VZMaxProf" , cms.double(0.2) ),
        ("VZMin" , cms.double(-30.0) ),
        ("VZMinProf" , cms.double(-0.2) ),
        ("X0Bin" , cms.int32(100) ),
        ("X0Max" , cms.double(0.5) ),
        ("X0Min" , cms.double(-0.5) ),
        ("Y0Bin" , cms.int32(100) ),
        ("Y0Max" , cms.double(0.5) ),
        ("Y0Min" , cms.double(-0.5) ),
        ("Z0Bin" , cms.int32(120) ),
        ("Z0Max" , cms.double(60.0) ),
        ("Z0Min" , cms.double(-60.0) ),
        ("allTrackProducer" , cms.InputTag("generalTracks") ),
        ("beamSpot" , cms.InputTag("offlineBeamSpot") ),
        ("denCut" , cms.string(' pt >= 1 ') ),
        ("doAllPlots" , cms.bool(False) ),
        ("doAllTrackCandHistos" , cms.bool(False) ),
        ("doBeamSpotPlots" , cms.bool(False) ),
        ("doDCAPlots" , cms.bool(False) ),
        ("doDCAwrt000Plots" , cms.bool(False) ),
        ("doDCAwrtPVPlots" , cms.bool(False) ),
        ("doEffFromHitPatternVsBX" , cms.bool(False) ),
        ("doEffFromHitPatternVsLUMI" , cms.bool(False) ),
        ("doEffFromHitPatternVsPU" , cms.bool(False) ),
        ("doGeneralPropertiesPlots" , cms.bool(False) ),
        ("doHIPlots" , cms.bool(False) ),
        ("doHitPropertiesPlots" , cms.bool(False) ),
        ("doLayersVsPhiVsEtaPerTrack" , cms.bool(False) ),
    ] +
    [
        ("doLumiAnalysis" , cms.bool(False) ),
        ("doMVAPlots" , cms.bool(False) ),
        ("doMeasurementStatePlots" , cms.bool(False) ),
        ("doPUmonitoring" , cms.bool(False) ),
        ("doPlotsVsBX" , cms.bool(False) ),
        ("doPlotsVsBXlumi" , cms.bool(False) ),
        ("doPlotsVsGoodPVtx" , cms.bool(True) ),
        ("doPlotsVsLUMI" , cms.bool(False) ),
        ("doPrimaryVertexPlots" , cms.bool(False) ),
        ("doProfilesVsLS" , cms.bool(False) ),
        ("doRecHitVsPhiVsEtaPerTrack" , cms.bool(False) ),
        ("doRecHitVsPtVsEtaPerTrack" , cms.bool(False) ),
        ("doRecHitsPerTrackProfile" , cms.bool(False) ),
        ("doRegionCandidatePlots" , cms.bool(False) ),
        ("doRegionPlots" , cms.bool(False) ),
        ("doSIPPlots" , cms.bool(False) ),
        ("doSeedDxyHisto" , cms.bool(False) ),
        ("doSeedDzHisto" , cms.bool(False) ),
        ("doSeedETAHisto" , cms.bool(True) ),
        ("doSeedLumiAnalysis" , cms.bool(True) ),
        ("doSeedNRecHitsHisto" , cms.bool(False) ),
        ("doSeedNVsEtaProf" , cms.bool(False) ),
        ("doSeedNVsPhiProf" , cms.bool(False) ),
        ("doSeedNumberHisto" , cms.bool(True) ),
        ("doSeedPHIHisto" , cms.bool(True) ),
        ("doSeedPHIVsETAHisto" , cms.bool(True) ),
        ("doSeedPTHisto" , cms.bool(True) ),
        ("doSeedParameterHistos" , cms.bool(False) ),
        ("doSeedQHisto" , cms.bool(False) ),
        ("doSeedThetaHisto" , cms.bool(False) ),
        ("doSeedVsClusterHisto" , cms.bool(True) ),
        ("doStopSource" , cms.bool(True) ),
        ("doTestPlots" , cms.bool(False) ),
        ("doThetaPlots" , cms.bool(False) ),
        ("doTrackCandHistos" , cms.bool(True) ),
        ("doTrackPxPyPlots" , cms.bool(False) ),
        ("doTrackerSpecific" , cms.bool(False) ),
        ("etaErrBin" , cms.int32(50) ),
        ("etaErrMax" , cms.double(0.1) ),
        ("etaErrMin" , cms.double(0.0) ),
        ("genericTriggerEventPSet" , cms.PSet(

    ) ),
        ("minNumberOfPixelsPerCluster" , cms.int32(2) ),
        ("minPixelClusterCharge" , cms.double(15000.0) ),
        ("numCut" , cms.string(" pt >= 1 & quality(\'highPurity\') ") ),
        ("pErrBin" , cms.int32(50) ),
        ("pErrMax" , cms.double(1.0) ),
        ("pErrMin" , cms.double(0.0) ),
        ("phiErrBin" , cms.int32(50) ),
        ("phiErrMax" , cms.double(0.1) ),
        ("phiErrMin" , cms.double(0.0) ),
        ("pixelCluster" , cms.InputTag("siPixelClusters") ),
        ("pixelCluster4lumi" , cms.InputTag("siPixelClustersPreSplitting") ),
        ("primaryVertex" , cms.InputTag("offlinePrimaryVertices") ),
        ("primaryVertexInputTags" , cms.VInputTag() ),
        ("ptErrBin" , cms.int32(50) ),
        ("ptErrMax" , cms.double(1.0) ),
        ("ptErrMin" , cms.double(0.0) ),
        ("pvLabels" , cms.vstring() ),
        ("pvNDOF" , cms.int32(4) ),
        ("pxErrBin" , cms.int32(50) ),
        ("pxErrMax" , cms.double(1.0) ),
        ("pxErrMin" , cms.double(0.0) ),
        ("pyErrBin" , cms.int32(50) ),
        ("pyErrMax" , cms.double(1.0) ),
        ("pyErrMin" , cms.double(0.0) ),
        ("pzErrBin" , cms.int32(50) ),
        ("pzErrMax" , cms.double(1.0) ),
        ("pzErrMin" , cms.double(0.0) ),
        ("qualityString" , cms.string('highPurity') ),
        ("scal" , cms.InputTag("scalersRawToDigi") ),
        ("selPrimaryVertexInputTags" , cms.VInputTag() ),
        ("stripCluster" , cms.InputTag("siStripClusters") ),
        ("subdetectorBin" , cms.int32(25) ),
        ("subdetectors" , cms.vstring(
        'TIB', 
        'TOB', 
        'TID', 
        'TEC', 
        'PixBarrel', 
        'PixEndcap', 
        'Pixel', 
        'Strip'
    ) ),
        ("useBPixLayer1" , cms.bool(False) ),
        ]
    )
)


TrackSeedMoninitialStep = cms.EDProducer("TrackingMonitor",
**dict(
    [
        ("AbsDxyBin" , cms.int32(120) ),
        ("AbsDxyMax" , cms.double(60.0) ),
        ("AbsDxyMin" , cms.double(0.0) ),
        ("AlgoName" , cms.string('initialStep') ),
        ("BSFolderName" , cms.string('Tracking/TrackParameters/BeamSpotParameters') ),
        ("BXlumiSetup" , cms.PSet(
        BXlumiBin = cms.int32(400),
        BXlumiMax = cms.double(6000),
        BXlumiMin = cms.double(2000),
        lumi = cms.InputTag("lumiProducer"),
        lumiScale = cms.double(6.37)
    ) ),
        ("Chi2Bin" , cms.int32(50) ),
        ("Chi2Max" , cms.double(199.5) ),
        ("Chi2Min" , cms.double(-0.5) ),
        ("Chi2NDFBin" , cms.int32(50) ),
        ("Chi2NDFMax" , cms.double(19.5) ),
        ("Chi2NDFMin" , cms.double(-0.5) ),
        ("Chi2ProbBin" , cms.int32(100) ),
        ("Chi2ProbMax" , cms.double(1.0) ),
        ("Chi2ProbMin" , cms.double(0.0) ),
        ("ClusterLabels" , cms.vstring('Pix') ),
        ("DxyBin" , cms.int32(100) ),
        ("DxyErrBin" , cms.int32(200) ),
        ("DxyErrMax" , cms.double(0.1) ),
        ("DxyMax" , cms.double(0.5) ),
        ("DxyMin" , cms.double(-0.5) ),
        ("Eta2DBin" , cms.int32(26) ),
        ("EtaBin" , cms.int32(46) ),
        ("EtaMax" , cms.double(4.5) ),
        ("EtaMin" , cms.double(-4.5) ),
        ("FolderName" , cms.string('Tracking/TrackParameters/generalTracks') ),
        ("GoodPVtxBin" , cms.int32(200) ),
        ("GoodPVtxMax" , cms.double(200.0) ),
        ("GoodPVtxMin" , cms.double(0.0) ),
        ("LSBin" , cms.int32(2000) ),
        ("LSMax" , cms.double(2000.0) ),
        ("LSMin" , cms.double(0) ),
        ("LUMIBin" , cms.int32(700) ),
        ("LUMIMax" , cms.double(70000.0) ),
        ("LUMIMin" , cms.double(0.0) ),
        ("LongDCABins" , cms.int32(100) ),
        ("LongDCAMax" , cms.double(8.0) ),
        ("LongDCAMin" , cms.double(-8.0) ),
        ("MVABin" , cms.int32(100) ),
        ("MVAMax" , cms.double(1) ),
        ("MVAMin" , cms.double(-1) ),
        ("MVAProducers" , cms.vstring(
        'initialStepClassifier1', 
        'initialStepClassifier2'
    ) ),
        ("MeanHitBin" , cms.int32(30) ),
        ("MeanHitMax" , cms.double(29.5) ),
        ("MeanHitMin" , cms.double(-0.5) ),
        ("MeanLayBin" , cms.int32(25) ),
        ("MeanLayMax" , cms.double(24.5) ),
        ("MeanLayMin" , cms.double(-0.5) ),
        ("MeasurementState" , cms.string('ImpactPoint') ),
        ("NClusPxBin" , cms.int32(100) ),
        ("NClusPxMax" , cms.double(20000) ),
        ("NClusPxMin" , cms.double(-0.5) ),
        ("NClusStrBin" , cms.int32(500) ),
        ("NClusStrMax" , cms.double(199999.5) ),
        ("NClusStrMin" , cms.double(-0.5) ),
        ("NTrk2DBin" , cms.int32(50) ),
        ("NTrk2DMax" , cms.double(1999.5) ),
        ("NTrk2DMin" , cms.double(-0.5) ),
        ("PVBin" , cms.int32(125) ),
        ("PVFolderName" , cms.string('Tracking/PrimaryVertices') ),
        ("PVMax" , cms.double(249.5) ),
        ("PVMin" , cms.double(-0.5) ),
        ("PXBLayBin" , cms.int32(6) ),
        ("PXBLayMax" , cms.double(5.5) ),
        ("PXBLayMin" , cms.double(-0.5) ),
        ("PXFLayBin" , cms.int32(6) ),
        ("PXFLayMax" , cms.double(5.5) ),
        ("PXFLayMin" , cms.double(-0.5) ),
        ("Phi2DBin" , cms.int32(32) ),
        ("PhiBin" , cms.int32(32) ),
        ("PhiMax" , cms.double(3.141592654) ),
        ("PhiMin" , cms.double(-3.141592654) ),
        ("Quality" , cms.string('') ),
        ("RecHitBin" , cms.int32(40) ),
        ("RecHitMax" , cms.double(39.5) ),
        ("RecHitMin" , cms.double(-0.5) ),
        ("RecLayBin" , cms.int32(25) ),
        ("RecLayMax" , cms.double(24.5) ),
        ("RecLayMin" , cms.double(-0.5) ),
        ("RecLostBin" , cms.int32(10) ),
        ("RecLostMax" , cms.double(9.5) ),
        ("RecLostMin" , cms.double(-0.5) ),
        ("RegionCandidatePtBin" , cms.int32(100) ),
        ("RegionCandidatePtMax" , cms.double(1000) ),
        ("RegionCandidatePtMin" , cms.double(0) ),
        ("RegionCandidates" , cms.InputTag("") ),
        ("RegionProducer" , cms.InputTag("") ),
        ("RegionSeedingLayersProducer" , cms.InputTag("") ),
        ("RegionSizeBin" , cms.int32(20) ),
        ("RegionSizeMax" , cms.double(19.5) ),
        ("RegionSizeMin" , cms.double(-0.5) ),
        ("SeedCandBin" , cms.int32(20) ),
        ("SeedCandMax" , cms.double(19.5) ),
        ("SeedCandMin" , cms.double(-0.5) ),
        ("SeedDxyBin" , cms.int32(100) ),
        ("SeedDxyMax" , cms.double(0.5) ),
        ("SeedDxyMin" , cms.double(-0.5) ),
        ("SeedDzBin" , cms.int32(120) ),
        ("SeedDzMax" , cms.double(30.0) ),
        ("SeedDzMin" , cms.double(-30.0) ),
        ("SeedHitBin" , cms.int32(6) ),
        ("SeedHitMax" , cms.double(5.5) ),
        ("SeedHitMin" , cms.double(-0.5) ),
        ("SeedProducer" , cms.InputTag("initialStepSeeds") ),
        ("TCDxyBin" , cms.int32(100) ),
        ("TCDxyMax" , cms.double(100.0) ),
        ("TCDxyMin" , cms.double(-100.0) ),
        ("TCDzBin" , cms.int32(100) ),
        ("TCDzMax" , cms.double(400.0) ),
        ("TCDzMin" , cms.double(-400.0) ),
        ("TCHitBin" , cms.int32(40) ),
        ("TCHitMax" , cms.double(39.5) ),
        ("TCHitMin" , cms.double(-0.5) ),
        ("TCProducer" , cms.InputTag("initialStepTrackCandidates") ),
        ("TCSizeBin" , cms.int32(200) ),
        ("TCSizeMax" , cms.double(999.5) ),
        ("TCSizeMin" , cms.double(-0.5) ),
        ("TECLayBin" , cms.int32(15) ),
        ("TECLayMax" , cms.double(14.5) ),
        ("TECLayMin" , cms.double(-0.5) ),
        ("TIBLayBin" , cms.int32(6) ),
        ("TIBLayMax" , cms.double(5.5) ),
        ("TIBLayMin" , cms.double(-0.5) ),
        ("TIDLayBin" , cms.int32(6) ),
        ("TIDLayMax" , cms.double(5.5) ),
        ("TIDLayMin" , cms.double(-0.5) ),
        ("TOBLayBin" , cms.int32(10) ),
        ("TOBLayMax" , cms.double(9.5) ),
        ("TOBLayMin" , cms.double(-0.5) ),
        ("TTRHBuilder" , cms.string('WithTrackAngle') ),
        ("ThetaBin" , cms.int32(32) ),
        ("ThetaMax" , cms.double(3.2) ),
        ("ThetaMin" , cms.double(0.0) ),
        ("TkSeedSizeBin" , cms.int32(100) ),
        ("TkSeedSizeMax" , cms.double(5000) ),
        ("TkSeedSizeMin" , cms.double(0) ),
        ("TkSizeBin" , cms.int32(100) ),
        ("TkSizeMax" , cms.double(99.5) ),
        ("TkSizeMin" , cms.double(-0.5) ),
        ("TrackPBin" , cms.int32(100) ),
        ("TrackPMax" , cms.double(100) ),
        ("TrackPMin" , cms.double(0) ),
        ("TrackProducer" , cms.InputTag("generalTracks") ),
        ("TrackProducerForMVA" , cms.InputTag("initialStepTracks") ),
        ("TrackPt2DBin" , cms.int32(100) ),
        ("TrackPtBin" , cms.int32(100) ),
        ("TrackPtMax" , cms.double(100) ),
        ("TrackPtMin" , cms.double(0.1) ),
        ("TrackPxBin" , cms.int32(50) ),
        ("TrackPxMax" , cms.double(50.0) ),
        ("TrackPxMin" , cms.double(-50.0) ),
        ("TrackPyBin" , cms.int32(50) ),
        ("TrackPyMax" , cms.double(50.0) ),
        ("TrackPyMin" , cms.double(-50.0) ),
        ("TrackPzBin" , cms.int32(50) ),
        ("TrackPzMax" , cms.double(50.0) ),
        ("TrackPzMin" , cms.double(-50.0) ),
        ("TrackQBin" , cms.int32(8) ),
        ("TrackQMax" , cms.double(2.5) ),
        ("TrackQMin" , cms.double(-2.5) ),
        ("TransDCABins" , cms.int32(100) ),
        ("TransDCAMax" , cms.double(8.0) ),
        ("TransDCAMin" , cms.double(-8.0) ),
        ("VXBin" , cms.int32(100) ),
        ("VXMax" , cms.double(0.5) ),
        ("VXMin" , cms.double(-0.5) ),
        ("VYBin" , cms.int32(100) ),
        ("VYMax" , cms.double(0.5) ),
        ("VYMin" , cms.double(-0.5) ),
        ("VZBin" , cms.int32(100) ),
        ("VZBinProf" , cms.int32(100) ),
        ("VZMax" , cms.double(30.0) ),
        ("VZMaxProf" , cms.double(0.2) ),
        ("VZMin" , cms.double(-30.0) ),
        ("VZMinProf" , cms.double(-0.2) ),
        ("X0Bin" , cms.int32(100) ),
        ("X0Max" , cms.double(0.5) ),
        ("X0Min" , cms.double(-0.5) ),
        ("Y0Bin" , cms.int32(100) ),
        ("Y0Max" , cms.double(0.5) ),
        ("Y0Min" , cms.double(-0.5) ),
        ("Z0Bin" , cms.int32(120) ),
        ("Z0Max" , cms.double(60.0) ),
        ("Z0Min" , cms.double(-60.0) ),
        ("allTrackProducer" , cms.InputTag("generalTracks") ),
        ("beamSpot" , cms.InputTag("offlineBeamSpot") ),
        ("denCut" , cms.string(' pt >= 1 ') ),
        ("doAllPlots" , cms.bool(False) ),
        ("doAllTrackCandHistos" , cms.bool(False) ),
        ("doBeamSpotPlots" , cms.bool(False) ),
        ("doDCAPlots" , cms.bool(False) ),
        ("doDCAwrt000Plots" , cms.bool(False) ),
        ("doDCAwrtPVPlots" , cms.bool(False) ),
        ("doEffFromHitPatternVsBX" , cms.bool(False) ),
        ("doEffFromHitPatternVsLUMI" , cms.bool(False) ),
        ("doEffFromHitPatternVsPU" , cms.bool(False) ),
        ("doGeneralPropertiesPlots" , cms.bool(False) ),
        ("doHIPlots" , cms.bool(False) ),
        ("doHitPropertiesPlots" , cms.bool(False) ),
        ("doLayersVsPhiVsEtaPerTrack" , cms.bool(False) ),
    ] +
    [
        ("doLumiAnalysis" , cms.bool(False) ),
        ("doMVAPlots" , cms.bool(False) ),
        ("doMeasurementStatePlots" , cms.bool(False) ),
        ("doPUmonitoring" , cms.bool(False) ),
        ("doPlotsVsBX" , cms.bool(False) ),
        ("doPlotsVsBXlumi" , cms.bool(False) ),
        ("doPlotsVsGoodPVtx" , cms.bool(True) ),
        ("doPlotsVsLUMI" , cms.bool(False) ),
        ("doPrimaryVertexPlots" , cms.bool(False) ),
        ("doProfilesVsLS" , cms.bool(False) ),
        ("doRecHitVsPhiVsEtaPerTrack" , cms.bool(False) ),
        ("doRecHitVsPtVsEtaPerTrack" , cms.bool(False) ),
        ("doRecHitsPerTrackProfile" , cms.bool(False) ),
        ("doRegionCandidatePlots" , cms.bool(False) ),
        ("doRegionPlots" , cms.bool(False) ),
        ("doSIPPlots" , cms.bool(False) ),
        ("doSeedDxyHisto" , cms.bool(False) ),
        ("doSeedDzHisto" , cms.bool(False) ),
        ("doSeedETAHisto" , cms.bool(True) ),
        ("doSeedLumiAnalysis" , cms.bool(True) ),
        ("doSeedNRecHitsHisto" , cms.bool(False) ),
        ("doSeedNVsEtaProf" , cms.bool(False) ),
        ("doSeedNVsPhiProf" , cms.bool(False) ),
        ("doSeedNumberHisto" , cms.bool(True) ),
        ("doSeedPHIHisto" , cms.bool(True) ),
        ("doSeedPHIVsETAHisto" , cms.bool(True) ),
        ("doSeedPTHisto" , cms.bool(True) ),
        ("doSeedParameterHistos" , cms.bool(False) ),
        ("doSeedQHisto" , cms.bool(False) ),
        ("doSeedThetaHisto" , cms.bool(False) ),
        ("doSeedVsClusterHisto" , cms.bool(True) ),
        ("doStopSource" , cms.bool(True) ),
        ("doTestPlots" , cms.bool(False) ),
        ("doThetaPlots" , cms.bool(False) ),
        ("doTrackCandHistos" , cms.bool(True) ),
        ("doTrackPxPyPlots" , cms.bool(False) ),
        ("doTrackerSpecific" , cms.bool(False) ),
        ("etaErrBin" , cms.int32(50) ),
        ("etaErrMax" , cms.double(0.1) ),
        ("etaErrMin" , cms.double(0.0) ),
        ("genericTriggerEventPSet" , cms.PSet(

    ) ),
        ("minNumberOfPixelsPerCluster" , cms.int32(2) ),
        ("minPixelClusterCharge" , cms.double(15000.0) ),
        ("numCut" , cms.string(" pt >= 1 & quality(\'highPurity\') ") ),
        ("pErrBin" , cms.int32(50) ),
        ("pErrMax" , cms.double(1.0) ),
        ("pErrMin" , cms.double(0.0) ),
        ("phiErrBin" , cms.int32(50) ),
        ("phiErrMax" , cms.double(0.1) ),
        ("phiErrMin" , cms.double(0.0) ),
        ("pixelCluster" , cms.InputTag("siPixelClusters") ),
        ("pixelCluster4lumi" , cms.InputTag("siPixelClustersPreSplitting") ),
        ("primaryVertex" , cms.InputTag("offlinePrimaryVertices") ),
        ("primaryVertexInputTags" , cms.VInputTag() ),
        ("ptErrBin" , cms.int32(50) ),
        ("ptErrMax" , cms.double(1.0) ),
        ("ptErrMin" , cms.double(0.0) ),
        ("pvLabels" , cms.vstring() ),
        ("pvNDOF" , cms.int32(4) ),
        ("pxErrBin" , cms.int32(50) ),
        ("pxErrMax" , cms.double(1.0) ),
        ("pxErrMin" , cms.double(0.0) ),
        ("pyErrBin" , cms.int32(50) ),
        ("pyErrMax" , cms.double(1.0) ),
        ("pyErrMin" , cms.double(0.0) ),
        ("pzErrBin" , cms.int32(50) ),
        ("pzErrMax" , cms.double(1.0) ),
        ("pzErrMin" , cms.double(0.0) ),
        ("qualityString" , cms.string('highPurity') ),
        ("scal" , cms.InputTag("scalersRawToDigi") ),
        ("selPrimaryVertexInputTags" , cms.VInputTag() ),
        ("stripCluster" , cms.InputTag("siStripClusters") ),
        ("subdetectorBin" , cms.int32(25) ),
        ("subdetectors" , cms.vstring(
        'TIB', 
        'TOB', 
        'TID', 
        'TEC', 
        'PixBarrel', 
        'PixEndcap', 
        'Pixel', 
        'Strip'
    ) ),
        ("useBPixLayer1" , cms.bool(False) ),
        ]
    )
)

TrackSplitMonitor = cms.EDProducer("TrackSplittingMonitor",
    FolderName = cms.string('Tracking/TrackParameters/SplitTracks'),
    d0Cut = cms.double(12.0),
    dcurvBin = cms.int32(100),
    dcurvMax = cms.double(0.005),
    dcurvMin = cms.double(-0.005),
    ddxyBin = cms.int32(100),
    ddxyMax = cms.double(200.0),
    ddxyMin = cms.double(-200.0),
    ddzBin = cms.int32(100),
    ddzMax = cms.double(400.0),
    ddzMin = cms.double(-400.0),
    dphiBin = cms.int32(100),
    dphiMax = cms.double(0.01),
    dphiMin = cms.double(-0.01),
    dptBin = cms.int32(100),
    dptMax = cms.double(5.0),
    dptMin = cms.double(-5.0),
    dthetaBin = cms.int32(100),
    dthetaMax = cms.double(0.01),
    dthetaMin = cms.double(-0.01),
    dzCut = cms.double(25.0),
    ifPlotMuons = cms.bool(True),
    norchiCut = cms.double(100.0),
    normBin = cms.int32(100),
    normMax = cms.double(5.0),
    normMin = cms.double(-5.0),
    pixelHitsPerLeg = cms.int32(1),
    ptCut = cms.double(4.0),
    splitMuonCollection = cms.InputTag("splitMuons"),
    splitTrackCollection = cms.InputTag("splittedTracksP5"),
    totalHitsPerLeg = cms.int32(6)
)

TrackerCollisionSelectedTrackMonCommongeneralTracks = cms.EDProducer("TrackingMonitor",
**dict(
    [
        ("AbsDxyBin" , cms.int32(120) ),
        ("AbsDxyMax" , cms.double(60.0) ),
        ("AbsDxyMin" , cms.double(0.0) ),
        ("AlgoName" , cms.string('GenTk') ),
        ("BSFolderName" , cms.string('Tracking/ParametersVsBeamSpot') ),
        ("BXlumiSetup" , cms.PSet(
        BXlumiBin = cms.int32(400),
        BXlumiMax = cms.double(6000),
        BXlumiMin = cms.double(2000),
        lumi = cms.InputTag("lumiProducer"),
        lumiScale = cms.double(6.37)
    ) ),
        ("Chi2Bin" , cms.int32(50) ),
        ("Chi2Max" , cms.double(199.5) ),
        ("Chi2Min" , cms.double(-0.5) ),
        ("Chi2NDFBin" , cms.int32(80) ),
        ("Chi2NDFMax" , cms.double(79.5) ),
        ("Chi2NDFMin" , cms.double(-0.5) ),
        ("Chi2ProbBin" , cms.int32(100) ),
        ("Chi2ProbMax" , cms.double(1.0) ),
        ("Chi2ProbMin" , cms.double(0.0) ),
        ("ClusterLabels" , cms.vstring(
        'Tot', 
        'Strip', 
        'Pix'
    ) ),
        ("DxyBin" , cms.int32(100) ),
        ("DxyErrBin" , cms.int32(200) ),
        ("DxyErrMax" , cms.double(0.1) ),
        ("DxyMax" , cms.double(0.5) ),
        ("DxyMin" , cms.double(-0.5) ),
        ("Eta2DBin" , cms.int32(26) ),
        ("EtaBin" , cms.int32(46) ),
        ("EtaMax" , cms.double(4.5) ),
        ("EtaMin" , cms.double(-4.5) ),
        ("FolderName" , cms.string('Tracking/TrackParameters/generalTracks') ),
        ("GoodPVtxBin" , cms.int32(60) ),
        ("GoodPVtxMax" , cms.double(60.0) ),
        ("GoodPVtxMin" , cms.double(0.0) ),
        ("LSBin" , cms.int32(2000) ),
        ("LSMax" , cms.double(2000.0) ),
        ("LSMin" , cms.double(0) ),
        ("LUMIBin" , cms.int32(700) ),
        ("LUMIMax" , cms.double(70000.0) ),
        ("LUMIMin" , cms.double(0.0) ),
        ("LongDCABins" , cms.int32(100) ),
        ("LongDCAMax" , cms.double(8.0) ),
        ("LongDCAMin" , cms.double(-8.0) ),
        ("MVABin" , cms.int32(100) ),
        ("MVAMax" , cms.double(1) ),
        ("MVAMin" , cms.double(-1) ),
        ("MVAProducers" , cms.vstring(
        'initialStepClassifier1', 
        'initialStepClassifier2'
    ) ),
        ("MeanHitBin" , cms.int32(30) ),
        ("MeanHitMax" , cms.double(29.5) ),
        ("MeanHitMin" , cms.double(-0.5) ),
        ("MeanLayBin" , cms.int32(25) ),
        ("MeanLayMax" , cms.double(24.5) ),
        ("MeanLayMin" , cms.double(-0.5) ),
        ("MeasurementState" , cms.string('ImpactPoint') ),
        ("NClusPxBin" , cms.int32(200) ),
        ("NClusPxMax" , cms.double(49999.5) ),
        ("NClusPxMin" , cms.double(-0.5) ),
        ("NClusStrBin" , cms.int32(500) ),
        ("NClusStrMax" , cms.double(199999.5) ),
        ("NClusStrMin" , cms.double(-0.5) ),
        ("NTrk2DBin" , cms.int32(50) ),
        ("NTrk2DMax" , cms.double(1999.5) ),
        ("NTrk2DMin" , cms.double(-0.5) ),
        ("PVBin" , cms.int32(125) ),
        ("PVFolderName" , cms.string('Tracking/PrimaryVertices/generalTracks') ),
        ("PVMax" , cms.double(249.5) ),
        ("PVMin" , cms.double(-0.5) ),
        ("PXBLayBin" , cms.int32(6) ),
        ("PXBLayMax" , cms.double(5.5) ),
        ("PXBLayMin" , cms.double(-0.5) ),
        ("PXFLayBin" , cms.int32(6) ),
        ("PXFLayMax" , cms.double(5.5) ),
        ("PXFLayMin" , cms.double(-0.5) ),
        ("Phi2DBin" , cms.int32(32) ),
        ("PhiBin" , cms.int32(32) ),
        ("PhiMax" , cms.double(3.141592654) ),
        ("PhiMin" , cms.double(-3.141592654) ),
        ("Quality" , cms.string('') ),
        ("RecHitBin" , cms.int32(40) ),
        ("RecHitMax" , cms.double(39.5) ),
        ("RecHitMin" , cms.double(-0.5) ),
        ("RecLayBin" , cms.int32(25) ),
        ("RecLayMax" , cms.double(24.5) ),
        ("RecLayMin" , cms.double(-0.5) ),
        ("RecLostBin" , cms.int32(10) ),
        ("RecLostMax" , cms.double(9.5) ),
        ("RecLostMin" , cms.double(-0.5) ),
        ("RegionCandidatePtBin" , cms.int32(100) ),
        ("RegionCandidatePtMax" , cms.double(1000) ),
        ("RegionCandidatePtMin" , cms.double(0) ),
        ("RegionCandidates" , cms.InputTag("") ),
        ("RegionProducer" , cms.InputTag("") ),
        ("RegionSeedingLayersProducer" , cms.InputTag("") ),
        ("RegionSizeBin" , cms.int32(20) ),
        ("RegionSizeMax" , cms.double(19.5) ),
        ("RegionSizeMin" , cms.double(-0.5) ),
        ("SeedCandBin" , cms.int32(20) ),
        ("SeedCandMax" , cms.double(19.5) ),
        ("SeedCandMin" , cms.double(-0.5) ),
        ("SeedDxyBin" , cms.int32(100) ),
        ("SeedDxyMax" , cms.double(0.5) ),
        ("SeedDxyMin" , cms.double(-0.5) ),
        ("SeedDzBin" , cms.int32(120) ),
        ("SeedDzMax" , cms.double(30.0) ),
        ("SeedDzMin" , cms.double(-30.0) ),
        ("SeedHitBin" , cms.int32(6) ),
        ("SeedHitMax" , cms.double(5.5) ),
        ("SeedHitMin" , cms.double(-0.5) ),
        ("SeedProducer" , cms.InputTag("initialStepSeeds") ),
        ("TCDxyBin" , cms.int32(100) ),
        ("TCDxyMax" , cms.double(100.0) ),
        ("TCDxyMin" , cms.double(-100.0) ),
        ("TCDzBin" , cms.int32(100) ),
        ("TCDzMax" , cms.double(400.0) ),
        ("TCDzMin" , cms.double(-400.0) ),
        ("TCHitBin" , cms.int32(40) ),
        ("TCHitMax" , cms.double(39.5) ),
        ("TCHitMin" , cms.double(-0.5) ),
        ("TCProducer" , cms.InputTag("initialStepTrackCandidates") ),
        ("TCSizeBin" , cms.int32(100) ),
        ("TCSizeMax" , cms.double(499.5) ),
        ("TCSizeMin" , cms.double(-0.5) ),
        ("TECLayBin" , cms.int32(15) ),
        ("TECLayMax" , cms.double(14.5) ),
        ("TECLayMin" , cms.double(-0.5) ),
        ("TIBLayBin" , cms.int32(6) ),
        ("TIBLayMax" , cms.double(5.5) ),
        ("TIBLayMin" , cms.double(-0.5) ),
        ("TIDLayBin" , cms.int32(6) ),
        ("TIDLayMax" , cms.double(5.5) ),
        ("TIDLayMin" , cms.double(-0.5) ),
        ("TOBLayBin" , cms.int32(10) ),
        ("TOBLayMax" , cms.double(9.5) ),
        ("TOBLayMin" , cms.double(-0.5) ),
        ("TTRHBuilder" , cms.string('WithTrackAngle') ),
        ("ThetaBin" , cms.int32(32) ),
        ("ThetaMax" , cms.double(3.2) ),
        ("ThetaMin" , cms.double(0.0) ),
        ("TkSeedSizeBin" , cms.int32(100) ),
        ("TkSeedSizeMax" , cms.double(499.5) ),
        ("TkSeedSizeMin" , cms.double(-0.5) ),
        ("TkSizeBin" , cms.int32(200) ),
        ("TkSizeMax" , cms.double(999.5) ),
        ("TkSizeMin" , cms.double(-0.5) ),
        ("TrackPBin" , cms.int32(100) ),
        ("TrackPMax" , cms.double(100.0) ),
        ("TrackPMin" , cms.double(0.0) ),
        ("TrackProducer" , cms.InputTag("generalTracks") ),
        ("TrackProducerForMVA" , cms.InputTag("initialStepTracks") ),
        ("TrackPt2DBin" , cms.int32(100) ),
        ("TrackPtBin" , cms.int32(100) ),
        ("TrackPtMax" , cms.double(100.0) ),
        ("TrackPtMin" , cms.double(0.0) ),
        ("TrackPxBin" , cms.int32(50) ),
        ("TrackPxMax" , cms.double(50.0) ),
        ("TrackPxMin" , cms.double(-50.0) ),
        ("TrackPyBin" , cms.int32(50) ),
        ("TrackPyMax" , cms.double(50.0) ),
        ("TrackPyMin" , cms.double(-50.0) ),
        ("TrackPzBin" , cms.int32(50) ),
        ("TrackPzMax" , cms.double(50.0) ),
        ("TrackPzMin" , cms.double(-50.0) ),
        ("TrackQBin" , cms.int32(8) ),
        ("TrackQMax" , cms.double(2.5) ),
        ("TrackQMin" , cms.double(-2.5) ),
        ("TransDCABins" , cms.int32(100) ),
        ("TransDCAMax" , cms.double(8.0) ),
        ("TransDCAMin" , cms.double(-8.0) ),
        ("VXBin" , cms.int32(100) ),
        ("VXMax" , cms.double(0.5) ),
        ("VXMin" , cms.double(-0.5) ),
        ("VYBin" , cms.int32(100) ),
        ("VYMax" , cms.double(0.5) ),
        ("VYMin" , cms.double(-0.5) ),
        ("VZBin" , cms.int32(100) ),
        ("VZBinProf" , cms.int32(100) ),
        ("VZMax" , cms.double(30.0) ),
        ("VZMaxProf" , cms.double(0.2) ),
        ("VZMin" , cms.double(-30.0) ),
        ("VZMinProf" , cms.double(-0.2) ),
        ("X0Bin" , cms.int32(100) ),
        ("X0Max" , cms.double(0.5) ),
        ("X0Min" , cms.double(-0.5) ),
        ("Y0Bin" , cms.int32(100) ),
        ("Y0Max" , cms.double(0.5) ),
        ("Y0Min" , cms.double(-0.5) ),
        ("Z0Bin" , cms.int32(120) ),
        ("Z0Max" , cms.double(60.0) ),
        ("Z0Min" , cms.double(-60.0) ),
        ("allTrackProducer" , cms.InputTag("generalTracks") ),
        ("beamSpot" , cms.InputTag("offlineBeamSpot") ),
        ("denCut" , cms.string('') ),
        ("doAllPlots" , cms.bool(False) ),
        ("doAllTrackCandHistos" , cms.bool(False) ),
        ("doBeamSpotPlots" , cms.bool(True) ),
        ("doDCAPlots" , cms.bool(False) ),
        ("doDCAwrt000Plots" , cms.bool(False) ),
        ("doDCAwrtPVPlots" , cms.bool(False) ),
        ("doEffFromHitPatternVsBX" , cms.bool(False) ),
        ("doEffFromHitPatternVsLUMI" , cms.bool(False) ),
        ("doEffFromHitPatternVsPU" , cms.bool(True) ),
        ("doGeneralPropertiesPlots" , cms.bool(True) ),
        ("doGoodTrackLayersVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doGoodTrackPlots" , cms.bool(True) ),
        ("doGoodTrackRecHitVsPhiVsEtaPerTrack" , cms.bool(True) ),
    ] +
    [
        ("doGoodTracksPlots" , cms.bool(True) ),
        ("doHIPlots" , cms.bool(False) ),
        ("doHitPropertiesPlots" , cms.bool(True) ),
        ("doLayersVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doLumiAnalysis" , cms.bool(True) ),
        ("doMVAPlots" , cms.bool(False) ),
        ("doMeasurementStatePlots" , cms.bool(True) ),
        ("doPUmonitoring" , cms.bool(False) ),
        ("doPlotsVsBX" , cms.bool(False) ),
        ("doPlotsVsBXlumi" , cms.bool(False) ),
        ("doPlotsVsGoodPVtx" , cms.bool(True) ),
        ("doPlotsVsLUMI" , cms.bool(False) ),
        ("doPrimaryVertexPlots" , cms.bool(False) ),
        ("doProfilesVsLS" , cms.bool(True) ),
        ("doRecHitVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doRecHitVsPtVsEtaPerTrack" , cms.bool(True) ),
        ("doRecHitsPerTrackProfile" , cms.bool(True) ),
        ("doRegionCandidatePlots" , cms.bool(False) ),
        ("doRegionPlots" , cms.bool(False) ),
        ("doSIPPlots" , cms.bool(False) ),
        ("doSeedDxyHisto" , cms.bool(False) ),
        ("doSeedDzHisto" , cms.bool(False) ),
        ("doSeedETAHisto" , cms.bool(False) ),
        ("doSeedLumiAnalysis" , cms.bool(False) ),
        ("doSeedNRecHitsHisto" , cms.bool(False) ),
        ("doSeedNVsEtaProf" , cms.bool(False) ),
        ("doSeedNVsPhiProf" , cms.bool(False) ),
        ("doSeedNumberHisto" , cms.bool(False) ),
        ("doSeedPHIHisto" , cms.bool(False) ),
        ("doSeedPHIVsETAHisto" , cms.bool(False) ),
        ("doSeedPTHisto" , cms.bool(False) ),
        ("doSeedParameterHistos" , cms.bool(False) ),
        ("doSeedQHisto" , cms.bool(False) ),
        ("doSeedThetaHisto" , cms.bool(False) ),
        ("doSeedVsClusterHisto" , cms.bool(False) ),
        ("doStopSource" , cms.bool(False) ),
        ("doTestPlots" , cms.bool(False) ),
        ("doThetaPlots" , cms.bool(False) ),
        ("doTrackCandHistos" , cms.bool(False) ),
        ("doTrackPxPyPlots" , cms.bool(False) ),
        ("doTrackerSpecific" , cms.bool(True) ),
        ("etaErrBin" , cms.int32(50) ),
        ("etaErrMax" , cms.double(0.1) ),
        ("etaErrMin" , cms.double(0.0) ),
        ("genericTriggerEventPSet" , cms.PSet(
        andOr = cms.bool(False),
        andOrDcs = cms.bool(False),
        dcsInputTag = cms.InputTag("scalersRawToDigi"),
        dcsPartitions = cms.vint32(
            24, 25, 26, 27, 28, 
            29
        ),
        errorReplyDcs = cms.bool(True)
    ) ),
        ("minNumberOfPixelsPerCluster" , cms.int32(2) ),
        ("minPixelClusterCharge" , cms.double(15000.0) ),
        ("numCut" , cms.string("quality(\'highPurity\')") ),
        ("pErrBin" , cms.int32(50) ),
        ("pErrMax" , cms.double(1.0) ),
        ("pErrMin" , cms.double(0.0) ),
        ("phiErrBin" , cms.int32(50) ),
        ("phiErrMax" , cms.double(0.1) ),
        ("phiErrMin" , cms.double(0.0) ),
        ("pixelCluster" , cms.InputTag("siPixelClusters") ),
        ("pixelCluster4lumi" , cms.InputTag("siPixelClustersPreSplitting") ),
        ("primaryVertex" , cms.InputTag("offlinePrimaryVertices") ),
        ("primaryVertexInputTags" , cms.VInputTag(cms.InputTag("offlinePrimaryVertices")) ),
        ("ptErrBin" , cms.int32(50) ),
        ("ptErrMax" , cms.double(1.0) ),
        ("ptErrMin" , cms.double(0.0) ),
        ("pvLabels" , cms.vstring('offline') ),
        ("pvNDOF" , cms.int32(4) ),
        ("pxErrBin" , cms.int32(50) ),
        ("pxErrMax" , cms.double(1.0) ),
        ("pxErrMin" , cms.double(0.0) ),
        ("pyErrBin" , cms.int32(50) ),
        ("pyErrMax" , cms.double(1.0) ),
        ("pyErrMin" , cms.double(0.0) ),
        ("pzErrBin" , cms.int32(50) ),
        ("pzErrMax" , cms.double(1.0) ),
        ("pzErrMin" , cms.double(0.0) ),
        ("qualityString" , cms.string('highPurity') ),
        ("scal" , cms.InputTag("scalersRawToDigi") ),
        ("selPrimaryVertexInputTags" , cms.VInputTag(cms.InputTag("goodOfflinePrimaryVertices")) ),
        ("stripCluster" , cms.InputTag("siStripClusters") ),
        ("subdetectorBin" , cms.int32(25) ),
        ("subdetectors" , cms.vstring(
        'TIB', 
        'TOB', 
        'TID', 
        'TEC', 
        'PixBarrel', 
        'PixEndcap', 
        'Pixel', 
        'Strip'
    ) ),
        ("useBPixLayer1" , cms.bool(False) ),
        ]
    )
)

TrackerCollisionSelectedTrackMonCommonhighPurityPV0p1 = cms.EDProducer("TrackingMonitor",
**dict(
    [
        ("AbsDxyBin" , cms.int32(120) ),
        ("AbsDxyMax" , cms.double(60.0) ),
        ("AbsDxyMin" , cms.double(0.0) ),
        ("AlgoName" , cms.string('GenTk') ),
        ("BSFolderName" , cms.string('Tracking/ParametersVsBeamSpot') ),
        ("BXlumiSetup" , cms.PSet(
        BXlumiBin = cms.int32(400),
        BXlumiMax = cms.double(6000),
        BXlumiMin = cms.double(2000),
        lumi = cms.InputTag("lumiProducer"),
        lumiScale = cms.double(6.37)
    ) ),
        ("Chi2Bin" , cms.int32(50) ),
        ("Chi2Max" , cms.double(199.5) ),
        ("Chi2Min" , cms.double(-0.5) ),
        ("Chi2NDFBin" , cms.int32(80) ),
        ("Chi2NDFMax" , cms.double(79.5) ),
        ("Chi2NDFMin" , cms.double(-0.5) ),
        ("Chi2ProbBin" , cms.int32(100) ),
        ("Chi2ProbMax" , cms.double(1.0) ),
        ("Chi2ProbMin" , cms.double(0.0) ),
        ("ClusterLabels" , cms.vstring(
        'Tot', 
        'Strip', 
        'Pix'
    ) ),
        ("DxyBin" , cms.int32(100) ),
        ("DxyErrBin" , cms.int32(200) ),
        ("DxyErrMax" , cms.double(0.1) ),
        ("DxyMax" , cms.double(0.5) ),
        ("DxyMin" , cms.double(-0.5) ),
        ("Eta2DBin" , cms.int32(26) ),
        ("EtaBin" , cms.int32(46) ),
        ("EtaMax" , cms.double(4.5) ),
        ("EtaMin" , cms.double(-4.5) ),
        ("FolderName" , cms.string('Tracking/TrackParameters/highPurityTracks/dzPV0p1') ),
        ("GoodPVtxBin" , cms.int32(60) ),
        ("GoodPVtxMax" , cms.double(60.0) ),
        ("GoodPVtxMin" , cms.double(0.0) ),
        ("LSBin" , cms.int32(2000) ),
        ("LSMax" , cms.double(2000.0) ),
        ("LSMin" , cms.double(0) ),
        ("LUMIBin" , cms.int32(700) ),
        ("LUMIMax" , cms.double(70000.0) ),
        ("LUMIMin" , cms.double(0.0) ),
        ("LongDCABins" , cms.int32(100) ),
        ("LongDCAMax" , cms.double(8.0) ),
        ("LongDCAMin" , cms.double(-8.0) ),
        ("MVABin" , cms.int32(100) ),
        ("MVAMax" , cms.double(1) ),
        ("MVAMin" , cms.double(-1) ),
        ("MVAProducers" , cms.vstring(
        'initialStepClassifier1', 
        'initialStepClassifier2'
    ) ),
        ("MeanHitBin" , cms.int32(30) ),
        ("MeanHitMax" , cms.double(29.5) ),
        ("MeanHitMin" , cms.double(-0.5) ),
        ("MeanLayBin" , cms.int32(25) ),
        ("MeanLayMax" , cms.double(24.5) ),
        ("MeanLayMin" , cms.double(-0.5) ),
        ("MeasurementState" , cms.string('ImpactPoint') ),
        ("NClusPxBin" , cms.int32(200) ),
        ("NClusPxMax" , cms.double(49999.5) ),
        ("NClusPxMin" , cms.double(-0.5) ),
        ("NClusStrBin" , cms.int32(500) ),
        ("NClusStrMax" , cms.double(199999.5) ),
        ("NClusStrMin" , cms.double(-0.5) ),
        ("NTrk2DBin" , cms.int32(50) ),
        ("NTrk2DMax" , cms.double(1999.5) ),
        ("NTrk2DMin" , cms.double(-0.5) ),
        ("PVBin" , cms.int32(125) ),
        ("PVFolderName" , cms.string('Tracking/PrimaryVertices/highPurityTracks/dzPV0p1') ),
        ("PVMax" , cms.double(249.5) ),
        ("PVMin" , cms.double(-0.5) ),
        ("PXBLayBin" , cms.int32(6) ),
        ("PXBLayMax" , cms.double(5.5) ),
        ("PXBLayMin" , cms.double(-0.5) ),
        ("PXFLayBin" , cms.int32(6) ),
        ("PXFLayMax" , cms.double(5.5) ),
        ("PXFLayMin" , cms.double(-0.5) ),
        ("Phi2DBin" , cms.int32(32) ),
        ("PhiBin" , cms.int32(32) ),
        ("PhiMax" , cms.double(3.141592654) ),
        ("PhiMin" , cms.double(-3.141592654) ),
        ("Quality" , cms.string('') ),
        ("RecHitBin" , cms.int32(40) ),
        ("RecHitMax" , cms.double(39.5) ),
        ("RecHitMin" , cms.double(-0.5) ),
        ("RecLayBin" , cms.int32(25) ),
        ("RecLayMax" , cms.double(24.5) ),
        ("RecLayMin" , cms.double(-0.5) ),
        ("RecLostBin" , cms.int32(10) ),
        ("RecLostMax" , cms.double(9.5) ),
        ("RecLostMin" , cms.double(-0.5) ),
        ("RegionCandidatePtBin" , cms.int32(100) ),
        ("RegionCandidatePtMax" , cms.double(1000) ),
        ("RegionCandidatePtMin" , cms.double(0) ),
        ("RegionCandidates" , cms.InputTag("") ),
        ("RegionProducer" , cms.InputTag("") ),
        ("RegionSeedingLayersProducer" , cms.InputTag("") ),
        ("RegionSizeBin" , cms.int32(20) ),
        ("RegionSizeMax" , cms.double(19.5) ),
        ("RegionSizeMin" , cms.double(-0.5) ),
        ("SeedCandBin" , cms.int32(20) ),
        ("SeedCandMax" , cms.double(19.5) ),
        ("SeedCandMin" , cms.double(-0.5) ),
        ("SeedDxyBin" , cms.int32(100) ),
        ("SeedDxyMax" , cms.double(0.5) ),
        ("SeedDxyMin" , cms.double(-0.5) ),
        ("SeedDzBin" , cms.int32(120) ),
        ("SeedDzMax" , cms.double(30.0) ),
        ("SeedDzMin" , cms.double(-30.0) ),
        ("SeedHitBin" , cms.int32(6) ),
        ("SeedHitMax" , cms.double(5.5) ),
        ("SeedHitMin" , cms.double(-0.5) ),
        ("SeedProducer" , cms.InputTag("initialStepSeeds") ),
        ("TCDxyBin" , cms.int32(100) ),
        ("TCDxyMax" , cms.double(100.0) ),
        ("TCDxyMin" , cms.double(-100.0) ),
        ("TCDzBin" , cms.int32(100) ),
        ("TCDzMax" , cms.double(400.0) ),
        ("TCDzMin" , cms.double(-400.0) ),
        ("TCHitBin" , cms.int32(40) ),
        ("TCHitMax" , cms.double(39.5) ),
        ("TCHitMin" , cms.double(-0.5) ),
        ("TCProducer" , cms.InputTag("initialStepTrackCandidates") ),
        ("TCSizeBin" , cms.int32(100) ),
        ("TCSizeMax" , cms.double(499.5) ),
        ("TCSizeMin" , cms.double(-0.5) ),
        ("TECLayBin" , cms.int32(15) ),
        ("TECLayMax" , cms.double(14.5) ),
        ("TECLayMin" , cms.double(-0.5) ),
        ("TIBLayBin" , cms.int32(6) ),
        ("TIBLayMax" , cms.double(5.5) ),
        ("TIBLayMin" , cms.double(-0.5) ),
        ("TIDLayBin" , cms.int32(6) ),
        ("TIDLayMax" , cms.double(5.5) ),
        ("TIDLayMin" , cms.double(-0.5) ),
        ("TOBLayBin" , cms.int32(10) ),
        ("TOBLayMax" , cms.double(9.5) ),
        ("TOBLayMin" , cms.double(-0.5) ),
        ("TTRHBuilder" , cms.string('WithTrackAngle') ),
        ("ThetaBin" , cms.int32(32) ),
        ("ThetaMax" , cms.double(3.2) ),
        ("ThetaMin" , cms.double(0.0) ),
        ("TkSeedSizeBin" , cms.int32(100) ),
        ("TkSeedSizeMax" , cms.double(499.5) ),
        ("TkSeedSizeMin" , cms.double(-0.5) ),
        ("TkSizeBin" , cms.int32(200) ),
        ("TkSizeMax" , cms.double(999.5) ),
        ("TkSizeMin" , cms.double(-0.5) ),
        ("TrackPBin" , cms.int32(100) ),
        ("TrackPMax" , cms.double(100.0) ),
        ("TrackPMin" , cms.double(0.0) ),
        ("TrackProducer" , cms.InputTag("highPurityPV0p1") ),
        ("TrackProducerForMVA" , cms.InputTag("initialStepTracks") ),
        ("TrackPt2DBin" , cms.int32(100) ),
        ("TrackPtBin" , cms.int32(100) ),
        ("TrackPtMax" , cms.double(100.0) ),
        ("TrackPtMin" , cms.double(0.0) ),
        ("TrackPxBin" , cms.int32(50) ),
        ("TrackPxMax" , cms.double(50.0) ),
        ("TrackPxMin" , cms.double(-50.0) ),
        ("TrackPyBin" , cms.int32(50) ),
        ("TrackPyMax" , cms.double(50.0) ),
        ("TrackPyMin" , cms.double(-50.0) ),
        ("TrackPzBin" , cms.int32(50) ),
        ("TrackPzMax" , cms.double(50.0) ),
        ("TrackPzMin" , cms.double(-50.0) ),
        ("TrackQBin" , cms.int32(8) ),
        ("TrackQMax" , cms.double(2.5) ),
        ("TrackQMin" , cms.double(-2.5) ),
        ("TransDCABins" , cms.int32(100) ),
        ("TransDCAMax" , cms.double(8.0) ),
        ("TransDCAMin" , cms.double(-8.0) ),
        ("VXBin" , cms.int32(100) ),
        ("VXMax" , cms.double(0.5) ),
        ("VXMin" , cms.double(-0.5) ),
        ("VYBin" , cms.int32(100) ),
        ("VYMax" , cms.double(0.5) ),
        ("VYMin" , cms.double(-0.5) ),
        ("VZBin" , cms.int32(100) ),
        ("VZBinProf" , cms.int32(100) ),
        ("VZMax" , cms.double(30.0) ),
        ("VZMaxProf" , cms.double(0.2) ),
        ("VZMin" , cms.double(-30.0) ),
        ("VZMinProf" , cms.double(-0.2) ),
        ("X0Bin" , cms.int32(100) ),
        ("X0Max" , cms.double(0.5) ),
        ("X0Min" , cms.double(-0.5) ),
        ("Y0Bin" , cms.int32(100) ),
        ("Y0Max" , cms.double(0.5) ),
        ("Y0Min" , cms.double(-0.5) ),
        ("Z0Bin" , cms.int32(120) ),
        ("Z0Max" , cms.double(60.0) ),
        ("Z0Min" , cms.double(-60.0) ),
        ("allTrackProducer" , cms.InputTag("PV0p1") ),
        ("beamSpot" , cms.InputTag("offlineBeamSpot") ),
        ("denCut" , cms.string('') ),
        ("doAllPlots" , cms.bool(False) ),
        ("doAllTrackCandHistos" , cms.bool(False) ),
        ("doBeamSpotPlots" , cms.bool(True) ),
        ("doDCAPlots" , cms.bool(True) ),
        ("doDCAwrt000Plots" , cms.bool(True) ),
        ("doDCAwrtPVPlots" , cms.bool(True) ),
        ("doEffFromHitPatternVsBX" , cms.bool(False) ),
        ("doEffFromHitPatternVsLUMI" , cms.bool(True) ),
        ("doEffFromHitPatternVsPU" , cms.bool(True) ),
        ("doGeneralPropertiesPlots" , cms.bool(True) ),
        ("doGoodTrackLayersVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doGoodTrackPlots" , cms.bool(True) ),
        ("doGoodTrackRecHitVsPhiVsEtaPerTrack" , cms.bool(True) ),
    ] +
    [
        ("doGoodTracksPlots" , cms.bool(True) ),
        ("doHIPlots" , cms.bool(False) ),
        ("doHitPropertiesPlots" , cms.bool(True) ),
        ("doLayersVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doLumiAnalysis" , cms.bool(True) ),
        ("doMVAPlots" , cms.bool(False) ),
        ("doMeasurementStatePlots" , cms.bool(True) ),
        ("doPUmonitoring" , cms.bool(False) ),
        ("doPlotsVsBX" , cms.bool(False) ),
        ("doPlotsVsBXlumi" , cms.bool(False) ),
        ("doPlotsVsGoodPVtx" , cms.bool(True) ),
        ("doPlotsVsLUMI" , cms.bool(False) ),
        ("doPrimaryVertexPlots" , cms.bool(False) ),
        ("doProfilesVsLS" , cms.bool(True) ),
        ("doRecHitVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doRecHitVsPtVsEtaPerTrack" , cms.bool(True) ),
        ("doRecHitsPerTrackProfile" , cms.bool(True) ),
        ("doRegionCandidatePlots" , cms.bool(False) ),
        ("doRegionPlots" , cms.bool(False) ),
        ("doSIPPlots" , cms.bool(True) ),
        ("doSeedDxyHisto" , cms.bool(False) ),
        ("doSeedDzHisto" , cms.bool(False) ),
        ("doSeedETAHisto" , cms.bool(False) ),
        ("doSeedLumiAnalysis" , cms.bool(False) ),
        ("doSeedNRecHitsHisto" , cms.bool(False) ),
        ("doSeedNVsEtaProf" , cms.bool(False) ),
        ("doSeedNVsPhiProf" , cms.bool(False) ),
        ("doSeedNumberHisto" , cms.bool(False) ),
        ("doSeedPHIHisto" , cms.bool(False) ),
        ("doSeedPHIVsETAHisto" , cms.bool(False) ),
        ("doSeedPTHisto" , cms.bool(False) ),
        ("doSeedParameterHistos" , cms.bool(False) ),
        ("doSeedQHisto" , cms.bool(False) ),
        ("doSeedThetaHisto" , cms.bool(False) ),
        ("doSeedVsClusterHisto" , cms.bool(False) ),
        ("doStopSource" , cms.bool(False) ),
        ("doTestPlots" , cms.bool(False) ),
        ("doThetaPlots" , cms.bool(False) ),
        ("doTrackCandHistos" , cms.bool(False) ),
        ("doTrackPxPyPlots" , cms.bool(False) ),
        ("doTrackerSpecific" , cms.bool(True) ),
        ("etaErrBin" , cms.int32(50) ),
        ("etaErrMax" , cms.double(0.1) ),
        ("etaErrMin" , cms.double(0.0) ),
        ("genericTriggerEventPSet" , cms.PSet(
        andOr = cms.bool(False),
        andOrDcs = cms.bool(False),
        dcsInputTag = cms.InputTag("scalersRawToDigi"),
        dcsPartitions = cms.vint32(
            24, 25, 26, 27, 28, 
            29
        ),
        errorReplyDcs = cms.bool(True)
    ) ),
        ("minNumberOfPixelsPerCluster" , cms.int32(2) ),
        ("minPixelClusterCharge" , cms.double(15000.0) ),
        ("numCut" , cms.string("quality(\'highPurity\')") ),
        ("pErrBin" , cms.int32(50) ),
        ("pErrMax" , cms.double(1.0) ),
        ("pErrMin" , cms.double(0.0) ),
        ("phiErrBin" , cms.int32(50) ),
        ("phiErrMax" , cms.double(0.1) ),
        ("phiErrMin" , cms.double(0.0) ),
        ("pixelCluster" , cms.InputTag("siPixelClusters") ),
        ("pixelCluster4lumi" , cms.InputTag("siPixelClustersPreSplitting") ),
        ("primaryVertex" , cms.InputTag("offlinePrimaryVertices") ),
        ("primaryVertexInputTags" , cms.VInputTag(cms.InputTag("offlinePrimaryVertices")) ),
        ("ptErrBin" , cms.int32(50) ),
        ("ptErrMax" , cms.double(1.0) ),
        ("ptErrMin" , cms.double(0.0) ),
        ("pvLabels" , cms.vstring('offline') ),
        ("pvNDOF" , cms.int32(4) ),
        ("pxErrBin" , cms.int32(50) ),
        ("pxErrMax" , cms.double(1.0) ),
        ("pxErrMin" , cms.double(0.0) ),
        ("pyErrBin" , cms.int32(50) ),
        ("pyErrMax" , cms.double(1.0) ),
        ("pyErrMin" , cms.double(0.0) ),
        ("pzErrBin" , cms.int32(50) ),
        ("pzErrMax" , cms.double(1.0) ),
        ("pzErrMin" , cms.double(0.0) ),
        ("qualityString" , cms.string('highPurity') ),
        ("scal" , cms.InputTag("scalersRawToDigi") ),
        ("selPrimaryVertexInputTags" , cms.VInputTag(cms.InputTag("goodOfflinePrimaryVertices")) ),
        ("stripCluster" , cms.InputTag("siStripClusters") ),
        ("subdetectorBin" , cms.int32(25) ),
        ("subdetectors" , cms.vstring(
        'TIB', 
        'TOB', 
        'TID', 
        'TEC', 
        'PixBarrel', 
        'PixEndcap', 
        'Pixel', 
        'Strip'
    ) ),
        ("useBPixLayer1" , cms.bool(False) ),
        ]
    )
)
TrackerCollisionSelectedTrackMonCommonhighPurityPt1 = cms.EDProducer("TrackingMonitor",
**dict(
    [
        ("AbsDxyBin" , cms.int32(120) ),
        ("AbsDxyMax" , cms.double(60.0) ),
        ("AbsDxyMin" , cms.double(0.0) ),
        ("AlgoName" , cms.string('GenTk') ),
        ("BSFolderName" , cms.string('Tracking/ParametersVsBeamSpot') ),
        ("BXlumiSetup" , cms.PSet(
        BXlumiBin = cms.int32(400),
        BXlumiMax = cms.double(6000),
        BXlumiMin = cms.double(2000),
        lumi = cms.InputTag("lumiProducer"),
        lumiScale = cms.double(6.37)
    ) ),
        ("Chi2Bin" , cms.int32(50) ),
        ("Chi2Max" , cms.double(199.5) ),
        ("Chi2Min" , cms.double(-0.5) ),
        ("Chi2NDFBin" , cms.int32(80) ),
        ("Chi2NDFMax" , cms.double(79.5) ),
        ("Chi2NDFMin" , cms.double(-0.5) ),
        ("Chi2ProbBin" , cms.int32(100) ),
        ("Chi2ProbMax" , cms.double(1.0) ),
        ("Chi2ProbMin" , cms.double(0.0) ),
        ("ClusterLabels" , cms.vstring(
        'Tot', 
        'Strip', 
        'Pix'
    ) ),
        ("DxyBin" , cms.int32(100) ),
        ("DxyErrBin" , cms.int32(200) ),
        ("DxyErrMax" , cms.double(0.1) ),
        ("DxyMax" , cms.double(0.5) ),
        ("DxyMin" , cms.double(-0.5) ),
        ("Eta2DBin" , cms.int32(26) ),
        ("EtaBin" , cms.int32(46) ),
        ("EtaMax" , cms.double(4.5) ),
        ("EtaMin" , cms.double(-4.5) ),
        ("FolderName" , cms.string('Tracking/TrackParameters/highPurityTracks/pt_1') ),
        ("GoodPVtxBin" , cms.int32(60) ),
        ("GoodPVtxMax" , cms.double(60.0) ),
        ("GoodPVtxMin" , cms.double(0.0) ),
        ("LSBin" , cms.int32(2000) ),
        ("LSMax" , cms.double(2000.0) ),
        ("LSMin" , cms.double(0) ),
        ("LUMIBin" , cms.int32(700) ),
        ("LUMIMax" , cms.double(70000.0) ),
        ("LUMIMin" , cms.double(0.0) ),
        ("LongDCABins" , cms.int32(100) ),
        ("LongDCAMax" , cms.double(8.0) ),
        ("LongDCAMin" , cms.double(-8.0) ),
        ("MVABin" , cms.int32(100) ),
        ("MVAMax" , cms.double(1) ),
        ("MVAMin" , cms.double(-1) ),
        ("MVAProducers" , cms.vstring(
        'initialStepClassifier1', 
        'initialStepClassifier2'
    ) ),
        ("MeanHitBin" , cms.int32(30) ),
        ("MeanHitMax" , cms.double(29.5) ),
        ("MeanHitMin" , cms.double(-0.5) ),
        ("MeanLayBin" , cms.int32(25) ),
        ("MeanLayMax" , cms.double(24.5) ),
        ("MeanLayMin" , cms.double(-0.5) ),
        ("MeasurementState" , cms.string('ImpactPoint') ),
        ("NClusPxBin" , cms.int32(200) ),
        ("NClusPxMax" , cms.double(49999.5) ),
        ("NClusPxMin" , cms.double(-0.5) ),
        ("NClusStrBin" , cms.int32(500) ),
        ("NClusStrMax" , cms.double(199999.5) ),
        ("NClusStrMin" , cms.double(-0.5) ),
        ("NTrk2DBin" , cms.int32(50) ),
        ("NTrk2DMax" , cms.double(1999.5) ),
        ("NTrk2DMin" , cms.double(-0.5) ),
        ("PVBin" , cms.int32(125) ),
        ("PVFolderName" , cms.string('Tracking/PrimaryVertices/highPurityTracks/pt_1') ),
        ("PVMax" , cms.double(249.5) ),
        ("PVMin" , cms.double(-0.5) ),
        ("PXBLayBin" , cms.int32(6) ),
        ("PXBLayMax" , cms.double(5.5) ),
        ("PXBLayMin" , cms.double(-0.5) ),
        ("PXFLayBin" , cms.int32(6) ),
        ("PXFLayMax" , cms.double(5.5) ),
        ("PXFLayMin" , cms.double(-0.5) ),
        ("Phi2DBin" , cms.int32(32) ),
        ("PhiBin" , cms.int32(32) ),
        ("PhiMax" , cms.double(3.141592654) ),
        ("PhiMin" , cms.double(-3.141592654) ),
        ("Quality" , cms.string('') ),
        ("RecHitBin" , cms.int32(40) ),
        ("RecHitMax" , cms.double(39.5) ),
        ("RecHitMin" , cms.double(-0.5) ),
        ("RecLayBin" , cms.int32(25) ),
        ("RecLayMax" , cms.double(24.5) ),
        ("RecLayMin" , cms.double(-0.5) ),
        ("RecLostBin" , cms.int32(10) ),
        ("RecLostMax" , cms.double(9.5) ),
        ("RecLostMin" , cms.double(-0.5) ),
        ("RegionCandidatePtBin" , cms.int32(100) ),
        ("RegionCandidatePtMax" , cms.double(1000) ),
        ("RegionCandidatePtMin" , cms.double(0) ),
        ("RegionCandidates" , cms.InputTag("") ),
        ("RegionProducer" , cms.InputTag("") ),
        ("RegionSeedingLayersProducer" , cms.InputTag("") ),
        ("RegionSizeBin" , cms.int32(20) ),
        ("RegionSizeMax" , cms.double(19.5) ),
        ("RegionSizeMin" , cms.double(-0.5) ),
        ("SeedCandBin" , cms.int32(20) ),
        ("SeedCandMax" , cms.double(19.5) ),
        ("SeedCandMin" , cms.double(-0.5) ),
        ("SeedDxyBin" , cms.int32(100) ),
        ("SeedDxyMax" , cms.double(0.5) ),
        ("SeedDxyMin" , cms.double(-0.5) ),
        ("SeedDzBin" , cms.int32(120) ),
        ("SeedDzMax" , cms.double(30.0) ),
        ("SeedDzMin" , cms.double(-30.0) ),
        ("SeedHitBin" , cms.int32(6) ),
        ("SeedHitMax" , cms.double(5.5) ),
        ("SeedHitMin" , cms.double(-0.5) ),
        ("SeedProducer" , cms.InputTag("initialStepSeeds") ),
        ("TCDxyBin" , cms.int32(100) ),
        ("TCDxyMax" , cms.double(100.0) ),
        ("TCDxyMin" , cms.double(-100.0) ),
        ("TCDzBin" , cms.int32(100) ),
        ("TCDzMax" , cms.double(400.0) ),
        ("TCDzMin" , cms.double(-400.0) ),
        ("TCHitBin" , cms.int32(40) ),
        ("TCHitMax" , cms.double(39.5) ),
        ("TCHitMin" , cms.double(-0.5) ),
        ("TCProducer" , cms.InputTag("initialStepTrackCandidates") ),
        ("TCSizeBin" , cms.int32(100) ),
        ("TCSizeMax" , cms.double(499.5) ),
        ("TCSizeMin" , cms.double(-0.5) ),
        ("TECLayBin" , cms.int32(15) ),
        ("TECLayMax" , cms.double(14.5) ),
        ("TECLayMin" , cms.double(-0.5) ),
        ("TIBLayBin" , cms.int32(6) ),
        ("TIBLayMax" , cms.double(5.5) ),
        ("TIBLayMin" , cms.double(-0.5) ),
        ("TIDLayBin" , cms.int32(6) ),
        ("TIDLayMax" , cms.double(5.5) ),
        ("TIDLayMin" , cms.double(-0.5) ),
        ("TOBLayBin" , cms.int32(10) ),
        ("TOBLayMax" , cms.double(9.5) ),
        ("TOBLayMin" , cms.double(-0.5) ),
        ("TTRHBuilder" , cms.string('WithTrackAngle') ),
        ("ThetaBin" , cms.int32(32) ),
        ("ThetaMax" , cms.double(3.2) ),
        ("ThetaMin" , cms.double(0.0) ),
        ("TkSeedSizeBin" , cms.int32(100) ),
        ("TkSeedSizeMax" , cms.double(499.5) ),
        ("TkSeedSizeMin" , cms.double(-0.5) ),
        ("TkSizeBin" , cms.int32(200) ),
        ("TkSizeMax" , cms.double(999.5) ),
        ("TkSizeMin" , cms.double(-0.5) ),
        ("TrackPBin" , cms.int32(100) ),
        ("TrackPMax" , cms.double(100.0) ),
        ("TrackPMin" , cms.double(0.0) ),
        ("TrackProducer" , cms.InputTag("highPurityPt1") ),
        ("TrackProducerForMVA" , cms.InputTag("initialStepTracks") ),
        ("TrackPt2DBin" , cms.int32(100) ),
        ("TrackPtBin" , cms.int32(100) ),
        ("TrackPtMax" , cms.double(100.0) ),
        ("TrackPtMin" , cms.double(0.0) ),
        ("TrackPxBin" , cms.int32(50) ),
        ("TrackPxMax" , cms.double(50.0) ),
        ("TrackPxMin" , cms.double(-50.0) ),
        ("TrackPyBin" , cms.int32(50) ),
        ("TrackPyMax" , cms.double(50.0) ),
        ("TrackPyMin" , cms.double(-50.0) ),
        ("TrackPzBin" , cms.int32(50) ),
        ("TrackPzMax" , cms.double(50.0) ),
        ("TrackPzMin" , cms.double(-50.0) ),
        ("TrackQBin" , cms.int32(8) ),
        ("TrackQMax" , cms.double(2.5) ),
        ("TrackQMin" , cms.double(-2.5) ),
        ("TransDCABins" , cms.int32(100) ),
        ("TransDCAMax" , cms.double(8.0) ),
        ("TransDCAMin" , cms.double(-8.0) ),
        ("VXBin" , cms.int32(100) ),
        ("VXMax" , cms.double(0.5) ),
        ("VXMin" , cms.double(-0.5) ),
        ("VYBin" , cms.int32(100) ),
        ("VYMax" , cms.double(0.5) ),
        ("VYMin" , cms.double(-0.5) ),
        ("VZBin" , cms.int32(100) ),
        ("VZBinProf" , cms.int32(100) ),
        ("VZMax" , cms.double(30.0) ),
        ("VZMaxProf" , cms.double(0.2) ),
        ("VZMin" , cms.double(-30.0) ),
        ("VZMinProf" , cms.double(-0.2) ),
        ("X0Bin" , cms.int32(100) ),
        ("X0Max" , cms.double(0.5) ),
        ("X0Min" , cms.double(-0.5) ),
        ("Y0Bin" , cms.int32(100) ),
        ("Y0Max" , cms.double(0.5) ),
        ("Y0Min" , cms.double(-0.5) ),
        ("Z0Bin" , cms.int32(120) ),
        ("Z0Max" , cms.double(60.0) ),
        ("Z0Min" , cms.double(-60.0) ),
        ("allTrackProducer" , cms.InputTag("generalTracks") ),
        ("beamSpot" , cms.InputTag("offlineBeamSpot") ),
        ("denCut" , cms.string(' pt >= 1 ') ),
        ("doAllPlots" , cms.bool(False) ),
        ("doAllTrackCandHistos" , cms.bool(False) ),
        ("doBeamSpotPlots" , cms.bool(True) ),
        ("doDCAPlots" , cms.bool(True) ),
        ("doDCAwrt000Plots" , cms.bool(True) ),
        ("doDCAwrtPVPlots" , cms.bool(True) ),
        ("doEffFromHitPatternVsBX" , cms.bool(False) ),
        ("doEffFromHitPatternVsLUMI" , cms.bool(True) ),
        ("doEffFromHitPatternVsPU" , cms.bool(True) ),
        ("doGeneralPropertiesPlots" , cms.bool(True) ),
        ("doGoodTrackLayersVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doGoodTrackPlots" , cms.bool(True) ),
        ("doGoodTrackRecHitVsPhiVsEtaPerTrack" , cms.bool(True) ),
    ] +
    [
        ("doGoodTracksPlots" , cms.bool(True) ),
        ("doHIPlots" , cms.bool(False) ),
        ("doHitPropertiesPlots" , cms.bool(True) ),
        ("doLayersVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doLumiAnalysis" , cms.bool(True) ),
        ("doMVAPlots" , cms.bool(False) ),
        ("doMeasurementStatePlots" , cms.bool(True) ),
        ("doPUmonitoring" , cms.bool(False) ),
        ("doPlotsVsBX" , cms.bool(False) ),
        ("doPlotsVsBXlumi" , cms.bool(False) ),
        ("doPlotsVsGoodPVtx" , cms.bool(True) ),
        ("doPlotsVsLUMI" , cms.bool(False) ),
        ("doPrimaryVertexPlots" , cms.bool(False) ),
        ("doProfilesVsLS" , cms.bool(True) ),
        ("doRecHitVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doRecHitVsPtVsEtaPerTrack" , cms.bool(True) ),
        ("doRecHitsPerTrackProfile" , cms.bool(True) ),
        ("doRegionCandidatePlots" , cms.bool(False) ),
        ("doRegionPlots" , cms.bool(False) ),
        ("doSIPPlots" , cms.bool(True) ),
        ("doSeedDxyHisto" , cms.bool(False) ),
        ("doSeedDzHisto" , cms.bool(False) ),
        ("doSeedETAHisto" , cms.bool(False) ),
        ("doSeedLumiAnalysis" , cms.bool(False) ),
        ("doSeedNRecHitsHisto" , cms.bool(False) ),
        ("doSeedNVsEtaProf" , cms.bool(False) ),
        ("doSeedNVsPhiProf" , cms.bool(False) ),
        ("doSeedNumberHisto" , cms.bool(False) ),
        ("doSeedPHIHisto" , cms.bool(False) ),
        ("doSeedPHIVsETAHisto" , cms.bool(False) ),
        ("doSeedPTHisto" , cms.bool(False) ),
        ("doSeedParameterHistos" , cms.bool(False) ),
        ("doSeedQHisto" , cms.bool(False) ),
        ("doSeedThetaHisto" , cms.bool(False) ),
        ("doSeedVsClusterHisto" , cms.bool(False) ),
        ("doStopSource" , cms.bool(False) ),
        ("doTestPlots" , cms.bool(False) ),
        ("doThetaPlots" , cms.bool(False) ),
        ("doTrackCandHistos" , cms.bool(False) ),
        ("doTrackPxPyPlots" , cms.bool(False) ),
        ("doTrackerSpecific" , cms.bool(True) ),
        ("etaErrBin" , cms.int32(50) ),
        ("etaErrMax" , cms.double(0.1) ),
        ("etaErrMin" , cms.double(0.0) ),
        ("genericTriggerEventPSet" , cms.PSet(
        andOr = cms.bool(False),
        andOrDcs = cms.bool(False),
        dcsInputTag = cms.InputTag("scalersRawToDigi"),
        dcsPartitions = cms.vint32(
            24, 25, 26, 27, 28, 
            29
        ),
        errorReplyDcs = cms.bool(True)
    ) ),
        ("minNumberOfPixelsPerCluster" , cms.int32(2) ),
        ("minPixelClusterCharge" , cms.double(15000.0) ),
        ("numCut" , cms.string(" pt >= 1 & quality(\'highPurity\')") ),
        ("pErrBin" , cms.int32(50) ),
        ("pErrMax" , cms.double(1.0) ),
        ("pErrMin" , cms.double(0.0) ),
        ("phiErrBin" , cms.int32(50) ),
        ("phiErrMax" , cms.double(0.1) ),
        ("phiErrMin" , cms.double(0.0) ),
        ("pixelCluster" , cms.InputTag("siPixelClusters") ),
        ("pixelCluster4lumi" , cms.InputTag("siPixelClustersPreSplitting") ),
        ("primaryVertex" , cms.InputTag("offlinePrimaryVertices") ),
        ("primaryVertexInputTags" , cms.VInputTag(cms.InputTag("offlinePrimaryVertices")) ),
        ("ptErrBin" , cms.int32(50) ),
        ("ptErrMax" , cms.double(1.0) ),
        ("ptErrMin" , cms.double(0.0) ),
        ("pvLabels" , cms.vstring('offline') ),
        ("pvNDOF" , cms.int32(4) ),
        ("pxErrBin" , cms.int32(50) ),
        ("pxErrMax" , cms.double(1.0) ),
        ("pxErrMin" , cms.double(0.0) ),
        ("pyErrBin" , cms.int32(50) ),
        ("pyErrMax" , cms.double(1.0) ),
        ("pyErrMin" , cms.double(0.0) ),
        ("pzErrBin" , cms.int32(50) ),
        ("pzErrMax" , cms.double(1.0) ),
        ("pzErrMin" , cms.double(0.0) ),
        ("qualityString" , cms.string('highPurity') ),
        ("scal" , cms.InputTag("scalersRawToDigi") ),
        ("selPrimaryVertexInputTags" , cms.VInputTag(cms.InputTag("goodOfflinePrimaryVertices")) ),
        ("stripCluster" , cms.InputTag("siStripClusters") ),
        ("subdetectorBin" , cms.int32(25) ),
        ("subdetectors" , cms.vstring(
        'TIB', 
        'TOB', 
        'TID', 
        'TEC', 
        'PixBarrel', 
        'PixEndcap', 
        'Pixel', 
        'Strip'
    ) ),
        ("useBPixLayer1" , cms.bool(False) ),
        ]
    )
)

TrackerCollisionSelectedTrackMonCommonhighPurityPtRange0to1 = cms.EDProducer("TrackingMonitor",
**dict(
    [
        ("AbsDxyBin" , cms.int32(120) ),
        ("AbsDxyMax" , cms.double(60.0) ),
        ("AbsDxyMin" , cms.double(0.0) ),
        ("AlgoName" , cms.string('GenTk') ),
        ("BSFolderName" , cms.string('Tracking/ParametersVsBeamSpot') ),
        ("BXlumiSetup" , cms.PSet(
        BXlumiBin = cms.int32(400),
        BXlumiMax = cms.double(6000),
        BXlumiMin = cms.double(2000),
        lumi = cms.InputTag("lumiProducer"),
        lumiScale = cms.double(6.37)
    ) ),
        ("Chi2Bin" , cms.int32(50) ),
        ("Chi2Max" , cms.double(199.5) ),
        ("Chi2Min" , cms.double(-0.5) ),
        ("Chi2NDFBin" , cms.int32(80) ),
        ("Chi2NDFMax" , cms.double(79.5) ),
        ("Chi2NDFMin" , cms.double(-0.5) ),
        ("Chi2ProbBin" , cms.int32(100) ),
        ("Chi2ProbMax" , cms.double(1.0) ),
        ("Chi2ProbMin" , cms.double(0.0) ),
        ("ClusterLabels" , cms.vstring(
        'Tot', 
        'Strip', 
        'Pix'
    ) ),
        ("DxyBin" , cms.int32(100) ),
        ("DxyErrBin" , cms.int32(200) ),
        ("DxyErrMax" , cms.double(0.1) ),
        ("DxyMax" , cms.double(0.5) ),
        ("DxyMin" , cms.double(-0.5) ),
        ("Eta2DBin" , cms.int32(26) ),
        ("EtaBin" , cms.int32(46) ),
        ("EtaMax" , cms.double(4.5) ),
        ("EtaMin" , cms.double(-4.5) ),
        ("FolderName" , cms.string('Tracking/TrackParameters/highPurityTracks/pt_0to1') ),
        ("GoodPVtxBin" , cms.int32(60) ),
        ("GoodPVtxMax" , cms.double(60.0) ),
        ("GoodPVtxMin" , cms.double(0.0) ),
        ("LSBin" , cms.int32(2000) ),
        ("LSMax" , cms.double(2000.0) ),
        ("LSMin" , cms.double(0) ),
        ("LUMIBin" , cms.int32(700) ),
        ("LUMIMax" , cms.double(70000.0) ),
        ("LUMIMin" , cms.double(0.0) ),
        ("LongDCABins" , cms.int32(100) ),
        ("LongDCAMax" , cms.double(8.0) ),
        ("LongDCAMin" , cms.double(-8.0) ),
        ("MVABin" , cms.int32(100) ),
        ("MVAMax" , cms.double(1) ),
        ("MVAMin" , cms.double(-1) ),
        ("MVAProducers" , cms.vstring(
        'initialStepClassifier1', 
        'initialStepClassifier2'
    ) ),
        ("MeanHitBin" , cms.int32(30) ),
        ("MeanHitMax" , cms.double(29.5) ),
        ("MeanHitMin" , cms.double(-0.5) ),
        ("MeanLayBin" , cms.int32(25) ),
        ("MeanLayMax" , cms.double(24.5) ),
        ("MeanLayMin" , cms.double(-0.5) ),
        ("MeasurementState" , cms.string('ImpactPoint') ),
        ("NClusPxBin" , cms.int32(200) ),
        ("NClusPxMax" , cms.double(49999.5) ),
        ("NClusPxMin" , cms.double(-0.5) ),
        ("NClusStrBin" , cms.int32(500) ),
        ("NClusStrMax" , cms.double(199999.5) ),
        ("NClusStrMin" , cms.double(-0.5) ),
        ("NTrk2DBin" , cms.int32(50) ),
        ("NTrk2DMax" , cms.double(1999.5) ),
        ("NTrk2DMin" , cms.double(-0.5) ),
        ("PVBin" , cms.int32(125) ),
        ("PVFolderName" , cms.string('Tracking/PrimaryVertices/highPurityTracks/pt_0to1') ),
        ("PVMax" , cms.double(249.5) ),
        ("PVMin" , cms.double(-0.5) ),
        ("PXBLayBin" , cms.int32(6) ),
        ("PXBLayMax" , cms.double(5.5) ),
        ("PXBLayMin" , cms.double(-0.5) ),
        ("PXFLayBin" , cms.int32(6) ),
        ("PXFLayMax" , cms.double(5.5) ),
        ("PXFLayMin" , cms.double(-0.5) ),
        ("Phi2DBin" , cms.int32(32) ),
        ("PhiBin" , cms.int32(32) ),
        ("PhiMax" , cms.double(3.141592654) ),
        ("PhiMin" , cms.double(-3.141592654) ),
        ("Quality" , cms.string('') ),
        ("RecHitBin" , cms.int32(40) ),
        ("RecHitMax" , cms.double(39.5) ),
        ("RecHitMin" , cms.double(-0.5) ),
        ("RecLayBin" , cms.int32(25) ),
        ("RecLayMax" , cms.double(24.5) ),
        ("RecLayMin" , cms.double(-0.5) ),
        ("RecLostBin" , cms.int32(10) ),
        ("RecLostMax" , cms.double(9.5) ),
        ("RecLostMin" , cms.double(-0.5) ),
        ("RegionCandidatePtBin" , cms.int32(100) ),
        ("RegionCandidatePtMax" , cms.double(1000) ),
        ("RegionCandidatePtMin" , cms.double(0) ),
        ("RegionCandidates" , cms.InputTag("") ),
        ("RegionProducer" , cms.InputTag("") ),
        ("RegionSeedingLayersProducer" , cms.InputTag("") ),
        ("RegionSizeBin" , cms.int32(20) ),
        ("RegionSizeMax" , cms.double(19.5) ),
        ("RegionSizeMin" , cms.double(-0.5) ),
        ("SeedCandBin" , cms.int32(20) ),
        ("SeedCandMax" , cms.double(19.5) ),
        ("SeedCandMin" , cms.double(-0.5) ),
        ("SeedDxyBin" , cms.int32(100) ),
        ("SeedDxyMax" , cms.double(0.5) ),
        ("SeedDxyMin" , cms.double(-0.5) ),
        ("SeedDzBin" , cms.int32(120) ),
        ("SeedDzMax" , cms.double(30.0) ),
        ("SeedDzMin" , cms.double(-30.0) ),
        ("SeedHitBin" , cms.int32(6) ),
        ("SeedHitMax" , cms.double(5.5) ),
        ("SeedHitMin" , cms.double(-0.5) ),
        ("SeedProducer" , cms.InputTag("initialStepSeeds") ),
        ("TCDxyBin" , cms.int32(100) ),
        ("TCDxyMax" , cms.double(100.0) ),
        ("TCDxyMin" , cms.double(-100.0) ),
        ("TCDzBin" , cms.int32(100) ),
        ("TCDzMax" , cms.double(400.0) ),
        ("TCDzMin" , cms.double(-400.0) ),
        ("TCHitBin" , cms.int32(40) ),
        ("TCHitMax" , cms.double(39.5) ),
        ("TCHitMin" , cms.double(-0.5) ),
        ("TCProducer" , cms.InputTag("initialStepTrackCandidates") ),
        ("TCSizeBin" , cms.int32(100) ),
        ("TCSizeMax" , cms.double(499.5) ),
        ("TCSizeMin" , cms.double(-0.5) ),
        ("TECLayBin" , cms.int32(15) ),
        ("TECLayMax" , cms.double(14.5) ),
        ("TECLayMin" , cms.double(-0.5) ),
        ("TIBLayBin" , cms.int32(6) ),
        ("TIBLayMax" , cms.double(5.5) ),
        ("TIBLayMin" , cms.double(-0.5) ),
        ("TIDLayBin" , cms.int32(6) ),
        ("TIDLayMax" , cms.double(5.5) ),
        ("TIDLayMin" , cms.double(-0.5) ),
        ("TOBLayBin" , cms.int32(10) ),
        ("TOBLayMax" , cms.double(9.5) ),
        ("TOBLayMin" , cms.double(-0.5) ),
        ("TTRHBuilder" , cms.string('WithTrackAngle') ),
        ("ThetaBin" , cms.int32(32) ),
        ("ThetaMax" , cms.double(3.2) ),
        ("ThetaMin" , cms.double(0.0) ),
        ("TkSeedSizeBin" , cms.int32(100) ),
        ("TkSeedSizeMax" , cms.double(499.5) ),
        ("TkSeedSizeMin" , cms.double(-0.5) ),
        ("TkSizeBin" , cms.int32(200) ),
        ("TkSizeMax" , cms.double(999.5) ),
        ("TkSizeMin" , cms.double(-0.5) ),
        ("TrackPBin" , cms.int32(10) ),
        ("TrackPMax" , cms.double(1.0) ),
        ("TrackPMin" , cms.double(0.0) ),
        ("TrackProducer" , cms.InputTag("highPurityPtRange0to1") ),
        ("TrackProducerForMVA" , cms.InputTag("initialStepTracks") ),
        ("TrackPt2DBin" , cms.int32(100) ),
        ("TrackPtBin" , cms.int32(10) ),
        ("TrackPtMax" , cms.double(1.0) ),
        ("TrackPtMin" , cms.double(0.0) ),
        ("TrackPxBin" , cms.int32(50) ),
        ("TrackPxMax" , cms.double(50.0) ),
        ("TrackPxMin" , cms.double(-50.0) ),
        ("TrackPyBin" , cms.int32(50) ),
        ("TrackPyMax" , cms.double(50.0) ),
        ("TrackPyMin" , cms.double(-50.0) ),
        ("TrackPzBin" , cms.int32(50) ),
        ("TrackPzMax" , cms.double(50.0) ),
        ("TrackPzMin" , cms.double(-50.0) ),
        ("TrackQBin" , cms.int32(8) ),
        ("TrackQMax" , cms.double(2.5) ),
        ("TrackQMin" , cms.double(-2.5) ),
        ("TransDCABins" , cms.int32(100) ),
        ("TransDCAMax" , cms.double(8.0) ),
        ("TransDCAMin" , cms.double(-8.0) ),
        ("VXBin" , cms.int32(100) ),
        ("VXMax" , cms.double(0.5) ),
        ("VXMin" , cms.double(-0.5) ),
        ("VYBin" , cms.int32(100) ),
        ("VYMax" , cms.double(0.5) ),
        ("VYMin" , cms.double(-0.5) ),
        ("VZBin" , cms.int32(100) ),
        ("VZBinProf" , cms.int32(100) ),
        ("VZMax" , cms.double(30.0) ),
        ("VZMaxProf" , cms.double(0.2) ),
        ("VZMin" , cms.double(-30.0) ),
        ("VZMinProf" , cms.double(-0.2) ),
        ("X0Bin" , cms.int32(100) ),
        ("X0Max" , cms.double(0.5) ),
        ("X0Min" , cms.double(-0.5) ),
        ("Y0Bin" , cms.int32(100) ),
        ("Y0Max" , cms.double(0.5) ),
        ("Y0Min" , cms.double(-0.5) ),
        ("Z0Bin" , cms.int32(120) ),
        ("Z0Max" , cms.double(60.0) ),
        ("Z0Min" , cms.double(-60.0) ),
        ("allTrackProducer" , cms.InputTag("generalTracks") ),
        ("beamSpot" , cms.InputTag("offlineBeamSpot") ),
        ("denCut" , cms.string(' pt >= 0 & pt < 1 ') ),
        ("doAllPlots" , cms.bool(False) ),
        ("doAllTrackCandHistos" , cms.bool(False) ),
        ("doBeamSpotPlots" , cms.bool(True) ),
        ("doDCAPlots" , cms.bool(False) ),
        ("doDCAwrt000Plots" , cms.bool(False) ),
        ("doDCAwrtPVPlots" , cms.bool(False) ),
        ("doEffFromHitPatternVsBX" , cms.bool(False) ),
        ("doEffFromHitPatternVsLUMI" , cms.bool(False) ),
        ("doEffFromHitPatternVsPU" , cms.bool(False) ),
        ("doGeneralPropertiesPlots" , cms.bool(True) ),
        ("doGoodTrackLayersVsPhiVsEtaPerTrack" , cms.bool(False) ),
        ("doGoodTrackPlots" , cms.bool(True) ),
        ("doGoodTrackRecHitVsPhiVsEtaPerTrack" , cms.bool(False) ),
    ] +
    [
        ("doGoodTracksPlots" , cms.bool(False) ),
        ("doHIPlots" , cms.bool(False) ),
        ("doHitPropertiesPlots" , cms.bool(True) ),
        ("doLayersVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doLumiAnalysis" , cms.bool(True) ),
        ("doMVAPlots" , cms.bool(False) ),
        ("doMeasurementStatePlots" , cms.bool(True) ),
        ("doPUmonitoring" , cms.bool(True) ),
        ("doPlotsVsBX" , cms.bool(False) ),
        ("doPlotsVsBXlumi" , cms.bool(False) ),
        ("doPlotsVsGoodPVtx" , cms.bool(True) ),
        ("doPlotsVsLUMI" , cms.bool(False) ),
        ("doPrimaryVertexPlots" , cms.bool(False) ),
        ("doProfilesVsLS" , cms.bool(True) ),
        ("doRecHitVsPhiVsEtaPerTrack" , cms.bool(True) ),
        ("doRecHitVsPtVsEtaPerTrack" , cms.bool(True) ),
        ("doRecHitsPerTrackProfile" , cms.bool(True) ),
        ("doRegionCandidatePlots" , cms.bool(False) ),
        ("doRegionPlots" , cms.bool(False) ),
        ("doSIPPlots" , cms.bool(False) ),
        ("doSeedDxyHisto" , cms.bool(False) ),
        ("doSeedDzHisto" , cms.bool(False) ),
        ("doSeedETAHisto" , cms.bool(False) ),
        ("doSeedLumiAnalysis" , cms.bool(False) ),
        ("doSeedNRecHitsHisto" , cms.bool(False) ),
        ("doSeedNVsEtaProf" , cms.bool(False) ),
        ("doSeedNVsPhiProf" , cms.bool(False) ),
        ("doSeedNumberHisto" , cms.bool(False) ),
        ("doSeedPHIHisto" , cms.bool(False) ),
        ("doSeedPHIVsETAHisto" , cms.bool(False) ),
        ("doSeedPTHisto" , cms.bool(False) ),
        ("doSeedParameterHistos" , cms.bool(False) ),
        ("doSeedQHisto" , cms.bool(False) ),
        ("doSeedThetaHisto" , cms.bool(False) ),
        ("doSeedVsClusterHisto" , cms.bool(False) ),
        ("doStopSource" , cms.bool(False) ),
        ("doTestPlots" , cms.bool(False) ),
        ("doThetaPlots" , cms.bool(False) ),
        ("doTrackCandHistos" , cms.bool(False) ),
        ("doTrackPxPyPlots" , cms.bool(False) ),
        ("doTrackerSpecific" , cms.bool(False) ),
        ("etaErrBin" , cms.int32(50) ),
        ("etaErrMax" , cms.double(0.1) ),
        ("etaErrMin" , cms.double(0.0) ),
        ("genericTriggerEventPSet" , cms.PSet(
        andOr = cms.bool(False),
        andOrDcs = cms.bool(False),
        dcsInputTag = cms.InputTag("scalersRawToDigi"),
        dcsPartitions = cms.vint32(
            24, 25, 26, 27, 28, 
            29
        ),
        errorReplyDcs = cms.bool(True)
    ) ),
        ("minNumberOfPixelsPerCluster" , cms.int32(2) ),
        ("minPixelClusterCharge" , cms.double(15000.0) ),
        ("numCut" , cms.string(" pt >= 0 & pt < 1 & quality(\'highPurity\')") ),
        ("pErrBin" , cms.int32(50) ),
        ("pErrMax" , cms.double(1.0) ),
        ("pErrMin" , cms.double(0.0) ),
        ("phiErrBin" , cms.int32(50) ),
        ("phiErrMax" , cms.double(0.1) ),
        ("phiErrMin" , cms.double(0.0) ),
        ("pixelCluster" , cms.InputTag("siPixelClusters") ),
        ("pixelCluster4lumi" , cms.InputTag("siPixelClustersPreSplitting") ),
        ("primaryVertex" , cms.InputTag("offlinePrimaryVertices") ),
        ("primaryVertexInputTags" , cms.VInputTag(cms.InputTag("offlinePrimaryVertices")) ),
        ("ptErrBin" , cms.int32(50) ),
        ("ptErrMax" , cms.double(1.0) ),
        ("ptErrMin" , cms.double(0.0) ),
        ("pvLabels" , cms.vstring('offline') ),
        ("pvNDOF" , cms.int32(4) ),
        ("pxErrBin" , cms.int32(50) ),
        ("pxErrMax" , cms.double(1.0) ),
        ("pxErrMin" , cms.double(0.0) ),
        ("pyErrBin" , cms.int32(50) ),
        ("pyErrMax" , cms.double(1.0) ),
        ("pyErrMin" , cms.double(0.0) ),
        ("pzErrBin" , cms.int32(50) ),
        ("pzErrMax" , cms.double(1.0) ),
        ("pzErrMin" , cms.double(0.0) ),
        ("qualityString" , cms.string('highPurity') ),
        ("scal" , cms.InputTag("scalersRawToDigi") ),
        ("selPrimaryVertexInputTags" , cms.VInputTag(cms.InputTag("goodOfflinePrimaryVertices")) ),
        ("stripCluster" , cms.InputTag("siStripClusters") ),
        ("subdetectorBin" , cms.int32(25) ),
        ("subdetectors" , cms.vstring(
        'TIB', 
        'TOB', 
        'TID', 
        'TEC', 
        'PixBarrel', 
        'PixEndcap', 
        'Pixel', 
        'Strip'
    ) ),
        ("useBPixLayer1" , cms.bool(False) ),
        ]
    )
)

dqmInfoTracking = cms.EDProducer("DQMEventInfo",
    subSystemFolder = cms.untracked.string('Tracking')
)

highPurityPV0p1 = cms.EDProducer("TrackWithVertexSelector",
    copyExtras = cms.untracked.bool(False),
    copyTrajectories = cms.untracked.bool(False),
    d0Max = cms.double(999.0),
    dzMax = cms.double(999.0),
    etaMax = cms.double(5.0),
    etaMin = cms.double(0.0),
    nSigmaDtVertex = cms.double(0),
    nVertices = cms.uint32(1),
    normalizedChi2 = cms.double(999999.0),
    numberOfLostHits = cms.uint32(999),
    numberOfValidHits = cms.uint32(0),
    numberOfValidPixelHits = cms.uint32(0),
    ptErrorCut = cms.double(9999999.0),
    ptMax = cms.double(100000.0),
    ptMin = cms.double(0.0),
    quality = cms.string('highPurity'),
    rhoVtx = cms.double(999.0),
    src = cms.InputTag("generalTracks"),
    timeResosTag = cms.InputTag(""),
    timesTag = cms.InputTag(""),
    useVtx = cms.bool(True),
    vertexTag = cms.InputTag("trackingDQMgoodOfflinePrimaryVertices"),
    vtxFallback = cms.bool(True),
    zetaVtx = cms.double(0.1)
)
highPurityPt1 = cms.EDFilter("TrackSelector",
    cut = cms.string("quality(\'highPurity\') & pt >= 1"),
    src = cms.InputTag("generalTracks")
)

highPurityPtRange0to1 = cms.EDFilter("TrackSelector",
    cut = cms.string("quality(\'highPurity\') & pt >= 0 & pt < 1 "),
    src = cms.InputTag("generalTracks")
)

primaryVertexResolution = cms.EDProducer("PrimaryVertexResolution",
    beamspotSrc = cms.untracked.InputTag("offlineBeamSpot"),
    binsNtracks = cms.untracked.int32(60),
    binsNvertices = cms.untracked.int32(100),
    binsPull = cms.untracked.int32(100),
    binsResol = cms.untracked.int32(100),
    lumiScalersSrc = cms.untracked.InputTag("scalersRawToDigi"),
    maxLumi = cms.untracked.double(20000),
    maxNtracks = cms.untracked.double(119.5),
    maxNvertices = cms.untracked.double(199.5),
    maxPt = cms.untracked.double(1000),
    maxPull = cms.untracked.double(5),
    maxResol = cms.untracked.double(0.02),
    minLumi = cms.untracked.double(200),
    minNtracks = cms.untracked.double(-0.5),
    minNvertices = cms.untracked.double(-0.5),
    minPt = cms.untracked.double(1),
    rootFolder = cms.untracked.string('OfflinePV/Resolution'),
    transientTrackBuilder = cms.untracked.string('TransientTrackBuilder'),
    vertexSrc = cms.untracked.InputTag("trackingDQMgoodOfflinePrimaryVertices")
)

pvMonitor = cms.EDProducer("PrimaryVertexMonitor",
    AlignmentLabel = cms.string('Alignment'),
    DxyBin = cms.int32(100),
    DxyMax = cms.double(5000.0),
    DxyMin = cms.double(-5000.0),
    DzBin = cms.int32(100),
    DzMax = cms.double(2000.0),
    DzMin = cms.double(-2000.0),
    EtaBin = cms.int32(41),
    EtaMax = cms.double(4.0),
    EtaMin = cms.double(-4.0),
    PhiBin = cms.int32(32),
    PhiMax = cms.double(3.141592654),
    PhiMin = cms.double(-3.141592654),
    TkSizeBin = cms.int32(100),
    TkSizeMax = cms.double(499.5),
    TkSizeMin = cms.double(-0.5),
    TopFolderName = cms.string('OfflinePV'),
    Xpos = cms.double(0.1),
    Ypos = cms.double(0.0),
    beamSpotLabel = cms.InputTag("offlineBeamSpot"),
    ndof = cms.int32(4),
    vertexLabel = cms.InputTag("offlinePrimaryVertices")
)

trackingDQMgoodOfflinePrimaryVertices = cms.EDFilter("VertexSelector",
    cut = cms.string('!isFake && ndof >= 4.0 && abs(z) <= 24.0 && abs(position.Rho) <= 2.0'),
    filter = cms.bool(False),
    src = cms.InputTag("offlinePrimaryVertices")
)

MC_Dqmoffline_v2 = cms.EndPath(cms.Task(PV0p1,TrackMon_ckf, TrackSeedMonhighPtTripletStep, TrackSeedMoninitialStep, TrackSplitMonitor, TrackerCollisionSelectedTrackMonCommongeneralTracks, TrackerCollisionSelectedTrackMonCommonhighPurityPV0p1, TrackerCollisionSelectedTrackMonCommonhighPurityPt1, TrackerCollisionSelectedTrackMonCommonhighPurityPtRange0to1,  dqmInfoTracking, highPurityPV0p1, highPurityPt1, highPurityPtRange0to1, primaryVertexResolution, pvMonitor, trackingDQMgoodOfflinePrimaryVertices))

